package me.biocomp.hubitat_ci.api.device_api.zwave.commands.networkmanagementinstallationmaintenancev2

trait PriorityRouteSet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.util.List getPayload()
    abstract java.lang.Short getRepeater1()
    abstract java.lang.Short getRepeater2()
    abstract java.lang.Short getRepeater3()
    abstract java.lang.Short getRepeater4()
    abstract java.lang.Short getRouteNodeId()
    abstract java.lang.Short getSPEED_100()
    abstract java.lang.Short getSPEED_40()
    abstract java.lang.Short getSPEED_9()
    abstract java.lang.Short getSpeed()
    abstract void setRepeater1(java.lang.Short a)
    abstract void setRepeater2(java.lang.Short a)
    abstract void setRepeater3(java.lang.Short a)
    abstract void setRepeater4(java.lang.Short a)
    abstract void setRouteNodeId(java.lang.Short a)
    abstract void setSPEED_100(java.lang.Short a)
    abstract void setSPEED_40(java.lang.Short a)
    abstract void setSPEED_9(java.lang.Short a)
    abstract void setSpeed(java.lang.Short a)
}
