package me.biocomp.hubitat_ci.api.device_api.zwave.commands.networkmanagementinstallationmaintenancev2

trait StatisticsReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.util.Map getNeighbors()
    abstract java.lang.Short getPacketErrorCount()
    abstract java.util.List getPayload()
    abstract java.lang.Short getRouteChanges()
    abstract java.lang.Short getRouteNodeId()
    abstract java.lang.Short getSPEED_100()
    abstract java.lang.Short getSPEED_40()
    abstract java.lang.Short getSPEED_9()
    abstract java.lang.Short getSTATISTIC_TYPE_NB()
    abstract java.lang.Short getSTATISTIC_TYPE_PEC()
    abstract java.lang.Short getSTATISTIC_TYPE_RC()
    abstract java.lang.Short getSTATISTIC_TYPE_TC()
    abstract java.lang.Short getSTATISTIC_TYPE_TS()
    abstract java.lang.Short getSTATISTIC_TYPE_TS2()
    abstract java.lang.Long getSumOfTransmissionTimes()
    abstract java.lang.Long getSumOfTransmissionTimesSquared()
    abstract java.lang.Short getTransmissionCount()
    abstract void setNeighbors(java.util.Map a)
    abstract void setPacketErrorCount(java.lang.Short a)
    abstract void setRouteChanges(java.lang.Short a)
    abstract void setRouteNodeId(java.lang.Short a)
    abstract void setSPEED_100(java.lang.Short a)
    abstract void setSPEED_40(java.lang.Short a)
    abstract void setSPEED_9(java.lang.Short a)
    abstract void setSTATISTIC_TYPE_NB(java.lang.Short a)
    abstract void setSTATISTIC_TYPE_PEC(java.lang.Short a)
    abstract void setSTATISTIC_TYPE_RC(java.lang.Short a)
    abstract void setSTATISTIC_TYPE_TC(java.lang.Short a)
    abstract void setSTATISTIC_TYPE_TS(java.lang.Short a)
    abstract void setSTATISTIC_TYPE_TS2(java.lang.Short a)
    abstract void setSumOfTransmissionTimes(java.lang.Long a)
    abstract void setSumOfTransmissionTimesSquared(java.lang.Long a)
    abstract void setTransmissionCount(java.lang.Short a)
}
