package me.biocomp.hubitat_ci.api.device_api.zwave.commands.thermostatmodev2

trait ThermostatModeSupportedReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getAuto()
    abstract java.lang.Boolean getAutoChangeover()
    abstract java.lang.Boolean getAuxiliaryemergencyHeat()
    abstract java.lang.Boolean getAway()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getCool()
    abstract java.lang.Boolean getDryAir()
    abstract java.lang.Boolean getEnergySaveCool()
    abstract java.lang.Boolean getEnergySaveHeat()
    abstract java.lang.Boolean getFanOnly()
    abstract java.lang.Boolean getFurnace()
    abstract java.lang.Boolean getHeat()
    abstract java.lang.Boolean getMoistAir()
    abstract java.lang.Boolean getOff()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getResume()
    abstract void setAuto(java.lang.Boolean a)
    abstract void setAutoChangeover(java.lang.Boolean a)
    abstract void setAuxiliaryemergencyHeat(java.lang.Boolean a)
    abstract void setAway(java.lang.Boolean a)
    abstract void setCool(java.lang.Boolean a)
    abstract void setDryAir(java.lang.Boolean a)
    abstract void setEnergySaveCool(java.lang.Boolean a)
    abstract void setEnergySaveHeat(java.lang.Boolean a)
    abstract void setFanOnly(java.lang.Boolean a)
    abstract void setFurnace(java.lang.Boolean a)
    abstract void setHeat(java.lang.Boolean a)
    abstract void setMoistAir(java.lang.Boolean a)
    abstract void setOff(java.lang.Boolean a)
    abstract void setResume(java.lang.Boolean a)
}
