package me.biocomp.hubitat_ci.api.common_api

trait ChildDeviceWrapper
{
    /*
     * Methods from reflection:
     * com.hubitat.app_api.ChildDeviceWrapper Methods:
        public void com.hubitat.app_api.DeviceWrapper.clearSetting(java.lang.String),
        public com.hubitat.hub.domain.State com.hubitat.app_api.DeviceWrapper.currentState(java.lang.String),
        public com.hubitat.hub.domain.State com.hubitat.app_api.DeviceWrapper.currentState(java.lang.String,boolean),
        public java.lang.Object com.hubitat.app_api.DeviceWrapper.currentValue(java.lang.String),
        public java.lang.Object com.hubitat.app_api.DeviceWrapper.currentValue(java.lang.String,boolean),
        public java.util.List com.hubitat.app_api.DeviceWrapper.events(),
        public java.util.List com.hubitat.app_api.DeviceWrapper.events(java.util.Map),
        public java.util.List com.hubitat.app_api.DeviceWrapper.eventsBetween(java.util.Date,java.util.Date),
        public java.util.List com.hubitat.app_api.DeviceWrapper.eventsBetween(java.util.Date,java.util.Date,java.util.Map),
        public java.util.List com.hubitat.app_api.DeviceWrapper.eventsSince(java.util.Date),
        public java.util.List com.hubitat.app_api.DeviceWrapper.eventsSince(java.util.Date,java.util.Map),
        public java.util.List com.hubitat.app_api.DeviceWrapper.getCapabilities(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getControllerType(),
        public java.util.List com.hubitat.app_api.DeviceWrapper.getCurrentStates(),
        public java.util.Map com.hubitat.app_api.DeviceWrapper.getData(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getDataValue(java.lang.String),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getDeviceDataByName(java.lang.String),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getDeviceNetworkId(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getDisplayName(),
        public java.lang.Long com.hubitat.app_api.DeviceWrapper.getDriverId(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getDriverType(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getEndpointId(),
        public com.hubitat.hub.domain.Hub com.hubitat.app_api.DeviceWrapper.getHub(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getId(),
        public java.lang.Long com.hubitat.app_api.DeviceWrapper.getIdAsLong(),
        public java.lang.Boolean com.hubitat.app_api.DeviceWrapper.getIsComponent(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getLabel(),
        public java.util.Date com.hubitat.app_api.DeviceWrapper.getLastActivity(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getName(),
        public java.lang.Long com.hubitat.app_api.DeviceWrapper.getParentAppId(),
        public java.lang.Long com.hubitat.app_api.DeviceWrapper.getParentDeviceId(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getStatus(),
        public java.util.List com.hubitat.app_api.DeviceWrapper.getSupportedAttributes(),
        public java.util.List com.hubitat.app_api.DeviceWrapper.getSupportedCommands(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getTypeName(),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.getZigbeeId(),
        public java.lang.Boolean com.hubitat.app_api.DeviceWrapper.hasAttribute(java.lang.String),
        public java.lang.Boolean com.hubitat.app_api.DeviceWrapper.hasCapability(java.lang.String),
        public java.lang.Boolean com.hubitat.app_api.DeviceWrapper.hasCommand(java.lang.String),
        public boolean com.hubitat.app_api.DeviceWrapper.isDisabled(),
        public com.hubitat.hub.domain.State com.hubitat.app_api.DeviceWrapper.latestState(java.lang.String),
        public com.hubitat.hub.domain.State com.hubitat.app_api.DeviceWrapper.latestState(java.lang.String,boolean),
        public java.lang.Object com.hubitat.app_api.DeviceWrapper.latestValue(java.lang.String),
        public java.lang.Object com.hubitat.app_api.DeviceWrapper.latestValue(java.lang.String,boolean),
        public java.lang.Object com.hubitat.app_api.DeviceWrapper.methodMissing(java.lang.String,java.lang.Object),
        public java.lang.Object com.hubitat.app_api.DeviceWrapper.propertyMissing(java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.removeSetting(java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.sendEvent(java.util.Map),
        public void com.hubitat.app_api.DeviceWrapper.setDeviceNetworkId(java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.setDisplayName(java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.setLabel(java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.setName(java.lang.String),
        public java.util.List com.hubitat.app_api.DeviceWrapper.statesSince(java.lang.String,java.util.Date),
        public java.util.List com.hubitat.app_api.DeviceWrapper.statesSince(java.lang.String,java.util.Date,java.util.Map),
        public java.lang.String com.hubitat.app_api.DeviceWrapper.toString(),
        public void com.hubitat.app_api.DeviceWrapper.updateDataValue(java.lang.String,java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.lang.Boolean),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.lang.Double),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.lang.Long),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.lang.String),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.util.Date),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.util.List),
        public void com.hubitat.app_api.DeviceWrapper.updateSetting(java.lang.String,java.util.Map),
        public java.lang.Object com.hubitat.app_api.ChildDeviceWrapper.methodMissing(java.lang.String,java.lang.Object)
     */
}
