package me.biocomp.hubitat_ci.api.device_api.zwave.commands.doorlockloggingv1

trait RecordReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getDay()
    abstract java.lang.Short getEventType()
    abstract java.lang.Short getHourLocalTime()
    abstract java.lang.Short getMinuteLocalTime()
    abstract java.lang.Short getMonth()
    abstract java.util.List getPayload()
    abstract java.lang.Short getRecordNumber()
    abstract java.lang.Short getRecordStatus()
    abstract java.lang.Short getSecondLocalTime()
    abstract java.util.List getUserCode()
    abstract java.lang.Short getUserCodeLength()
    abstract java.lang.Short getUserIdentifier()
    abstract java.lang.Integer getYear()
    abstract void setDay(java.lang.Short a)
    abstract void setEventType(java.lang.Short a)
    abstract void setHourLocalTime(java.lang.Short a)
    abstract void setMinuteLocalTime(java.lang.Short a)
    abstract void setMonth(java.lang.Short a)
    abstract void setRecordNumber(java.lang.Short a)
    abstract void setRecordStatus(java.lang.Short a)
    abstract void setSecondLocalTime(java.lang.Short a)
    abstract void setUserCode(java.util.List a)
    abstract void setUserCodeLength(java.lang.Short a)
    abstract void setUserIdentifier(java.lang.Short a)
    abstract void setYear(java.lang.Integer a)
}
