package me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1

trait ChimneyFanSetupSet {
    abstract java.lang.String format()
    abstract java.util.List getAlarmTemperatureValue()
    abstract java.lang.Short getBoostTime()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getMODE_OFF()
    abstract java.lang.Short getMODE_ON()
    abstract java.lang.Short getMinSpeed()
    abstract java.lang.Short getMode()
    abstract java.util.List getPayload()
    abstract java.lang.Short getPrecision1()
    abstract java.lang.Short getPrecision2()
    abstract java.lang.Short getPrecision3()
    abstract java.lang.Short getScale1()
    abstract java.lang.Short getScale2()
    abstract java.lang.Short getScale3()
    abstract java.lang.Short getSize1()
    abstract java.lang.Short getSize2()
    abstract java.lang.Short getSize3()
    abstract java.util.List getStartTemperature()
    abstract java.util.List getStopTemperature()
    abstract java.lang.Short getStopTime()
    abstract void setAlarmTemperatureValue(java.util.List a)
    abstract void setBoostTime(java.lang.Short a)
    abstract void setMODE_OFF(java.lang.Short a)
    abstract void setMODE_ON(java.lang.Short a)
    abstract void setMinSpeed(java.lang.Short a)
    abstract void setMode(java.lang.Short a)
    abstract void setPrecision1(java.lang.Short a)
    abstract void setPrecision2(java.lang.Short a)
    abstract void setPrecision3(java.lang.Short a)
    abstract void setScale1(java.lang.Short a)
    abstract void setScale2(java.lang.Short a)
    abstract void setScale3(java.lang.Short a)
    abstract void setSize1(java.lang.Short a)
    abstract void setSize2(java.lang.Short a)
    abstract void setSize3(java.lang.Short a)
    abstract void setStartTemperature(java.util.List a)
    abstract void setStopTemperature(java.util.List a)
    abstract void setStopTime(java.lang.Short a)
}
