package me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1

trait ChimneyFanStatusReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getAlarmTemperatureExceeded()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getExternalAlarm()
    abstract java.lang.Short getNotUsed()
    abstract java.util.List getPayload()
    abstract java.lang.Short getPrecision()
    abstract java.lang.Short getSTATE_BOOST()
    abstract java.lang.Short getSTATE_CHIMNEY_FIRE()
    abstract java.lang.Short getSTATE_EXHAUST()
    abstract java.lang.Short getSTATE_EXTERNAL_ALARM()
    abstract java.lang.Short getSTATE_OFF()
    abstract java.lang.Short getSTATE_RELOAD()
    abstract java.lang.Short getSTATE_SENSOR_FAILURE()
    abstract java.lang.Short getSTATE_SERVICE()
    abstract java.lang.Short getSTATE_STOP()
    abstract java.lang.Short getSTATE_VENTING()
    abstract java.lang.Short getSTATE_VENTING_EX()
    abstract java.lang.Short getScale()
    abstract java.math.BigDecimal getScaledValue()
    abstract java.lang.Boolean getSensorError()
    abstract java.lang.Boolean getService()
    abstract java.lang.Short getSize()
    abstract java.lang.Short getSpeed()
    abstract java.lang.Boolean getSpeedChangeEnable()
    abstract java.lang.Boolean getStartTemperatureExceeded()
    abstract java.lang.Short getState()
    abstract java.util.List getValue()
    abstract void setAlarmTemperatureExceeded(java.lang.Boolean a)
    abstract void setExternalAlarm(java.lang.Boolean a)
    abstract void setNotUsed(java.lang.Short a)
    abstract void setPrecision(java.lang.Short a)
    abstract void setSTATE_BOOST(java.lang.Short a)
    abstract void setSTATE_CHIMNEY_FIRE(java.lang.Short a)
    abstract void setSTATE_EXHAUST(java.lang.Short a)
    abstract void setSTATE_EXTERNAL_ALARM(java.lang.Short a)
    abstract void setSTATE_OFF(java.lang.Short a)
    abstract void setSTATE_RELOAD(java.lang.Short a)
    abstract void setSTATE_SENSOR_FAILURE(java.lang.Short a)
    abstract void setSTATE_SERVICE(java.lang.Short a)
    abstract void setSTATE_STOP(java.lang.Short a)
    abstract void setSTATE_VENTING(java.lang.Short a)
    abstract void setSTATE_VENTING_EX(java.lang.Short a)
    abstract void setScale(java.lang.Short a)
    abstract void setScaledValue(java.math.BigDecimal a)
    abstract void setSensorError(java.lang.Boolean a)
    abstract void setService(java.lang.Boolean a)
    abstract void setSize(java.lang.Short a)
    abstract void setSpeed(java.lang.Short a)
    abstract void setSpeedChangeEnable(java.lang.Boolean a)
    abstract void setStartTemperatureExceeded(java.lang.Boolean a)
    abstract void setState(java.lang.Short a)
    abstract void setValue(java.util.List a)
}
