package me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1

trait ChimneyFanStateReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSTATE_BOOST()
    abstract java.lang.Short getSTATE_CHIMNEY_FIRE()
    abstract java.lang.Short getSTATE_EXHAUST()
    abstract java.lang.Short getSTATE_EXTERNAL_ALARM()
    abstract java.lang.Short getSTATE_OFF()
    abstract java.lang.Short getSTATE_RELOAD()
    abstract java.lang.Short getSTATE_SENSOR_FAILURE()
    abstract java.lang.Short getSTATE_SERVICE()
    abstract java.lang.Short getSTATE_STOP()
    abstract java.lang.Short getSTATE_VENTING()
    abstract java.lang.Short getSTATE_VENTING_EX()
    abstract java.lang.Short getState()
    abstract void setSTATE_BOOST(java.lang.Short a)
    abstract void setSTATE_CHIMNEY_FIRE(java.lang.Short a)
    abstract void setSTATE_EXHAUST(java.lang.Short a)
    abstract void setSTATE_EXTERNAL_ALARM(java.lang.Short a)
    abstract void setSTATE_OFF(java.lang.Short a)
    abstract void setSTATE_RELOAD(java.lang.Short a)
    abstract void setSTATE_SENSOR_FAILURE(java.lang.Short a)
    abstract void setSTATE_SERVICE(java.lang.Short a)
    abstract void setSTATE_STOP(java.lang.Short a)
    abstract void setSTATE_VENTING(java.lang.Short a)
    abstract void setSTATE_VENTING_EX(java.lang.Short a)
    abstract void setState(java.lang.Short a)
}
