package me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1

trait ChimneyFanAlarmLogReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getAlarmStillActive1()
    abstract java.lang.Boolean getAlarmStillActive2()
    abstract java.lang.Boolean getAlarmStillActive3()
    abstract java.lang.Boolean getAlarmStillActive4()
    abstract java.lang.Boolean getAlarmStillActive5()
    abstract java.lang.Boolean getAlarmTemperatureExceeded1()
    abstract java.lang.Boolean getAlarmTemperatureExceeded2()
    abstract java.lang.Boolean getAlarmTemperatureExceeded3()
    abstract java.lang.Boolean getAlarmTemperatureExceeded4()
    abstract java.lang.Boolean getAlarmTemperatureExceeded5()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getExternalAlarm1()
    abstract java.lang.Boolean getExternalAlarm2()
    abstract java.lang.Boolean getExternalAlarm3()
    abstract java.lang.Boolean getExternalAlarm4()
    abstract java.lang.Boolean getExternalAlarm5()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getSensorError1()
    abstract java.lang.Boolean getSensorError2()
    abstract java.lang.Boolean getSensorError3()
    abstract java.lang.Boolean getSensorError4()
    abstract java.lang.Boolean getSensorError5()
    abstract void setAlarmStillActive1(java.lang.Boolean a)
    abstract void setAlarmStillActive2(java.lang.Boolean a)
    abstract void setAlarmStillActive3(java.lang.Boolean a)
    abstract void setAlarmStillActive4(java.lang.Boolean a)
    abstract void setAlarmStillActive5(java.lang.Boolean a)
    abstract void setAlarmTemperatureExceeded1(java.lang.Boolean a)
    abstract void setAlarmTemperatureExceeded2(java.lang.Boolean a)
    abstract void setAlarmTemperatureExceeded3(java.lang.Boolean a)
    abstract void setAlarmTemperatureExceeded4(java.lang.Boolean a)
    abstract void setAlarmTemperatureExceeded5(java.lang.Boolean a)
    abstract void setExternalAlarm1(java.lang.Boolean a)
    abstract void setExternalAlarm2(java.lang.Boolean a)
    abstract void setExternalAlarm3(java.lang.Boolean a)
    abstract void setExternalAlarm4(java.lang.Boolean a)
    abstract void setExternalAlarm5(java.lang.Boolean a)
    abstract void setSensorError1(java.lang.Boolean a)
    abstract void setSensorError2(java.lang.Boolean a)
    abstract void setSensorError3(java.lang.Boolean a)
    abstract void setSensorError4(java.lang.Boolean a)
    abstract void setSensorError5(java.lang.Boolean a)
}
