package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait ChimneyFanV1 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmLogGet chimneyFanAlarmLogGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmLogGet chimneyFanAlarmLogGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmLogReport chimneyFanAlarmLogReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmLogReport chimneyFanAlarmLogReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmLogSet chimneyFanAlarmLogSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmLogSet chimneyFanAlarmLogSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmStatusGet chimneyFanAlarmStatusGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmStatusGet chimneyFanAlarmStatusGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmStatusReport chimneyFanAlarmStatusReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmStatusReport chimneyFanAlarmStatusReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmStatusSet chimneyFanAlarmStatusSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmStatusSet chimneyFanAlarmStatusSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmTempGet chimneyFanAlarmTempGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmTempGet chimneyFanAlarmTempGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmTempReport chimneyFanAlarmTempReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmTempReport chimneyFanAlarmTempReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmTempSet chimneyFanAlarmTempSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanAlarmTempSet chimneyFanAlarmTempSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanBoostTimeGet chimneyFanBoostTimeGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanBoostTimeGet chimneyFanBoostTimeGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanBoostTimeReport chimneyFanBoostTimeReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanBoostTimeReport chimneyFanBoostTimeReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanBoostTimeSet chimneyFanBoostTimeSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanBoostTimeSet chimneyFanBoostTimeSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanDefaultSet chimneyFanDefaultSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanDefaultSet chimneyFanDefaultSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanMinSpeedGet chimneyFanMinSpeedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanMinSpeedGet chimneyFanMinSpeedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanMinSpeedReport chimneyFanMinSpeedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanMinSpeedReport chimneyFanMinSpeedReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanMinSpeedSet chimneyFanMinSpeedSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanMinSpeedSet chimneyFanMinSpeedSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanModeGet chimneyFanModeGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanModeGet chimneyFanModeGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanModeReport chimneyFanModeReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanModeReport chimneyFanModeReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanModeSet chimneyFanModeSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanModeSet chimneyFanModeSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSetupGet chimneyFanSetupGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSetupGet chimneyFanSetupGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSetupReport chimneyFanSetupReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSetupReport chimneyFanSetupReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSetupSet chimneyFanSetupSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSetupSet chimneyFanSetupSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSpeedGet chimneyFanSpeedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSpeedGet chimneyFanSpeedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSpeedReport chimneyFanSpeedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSpeedReport chimneyFanSpeedReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSpeedSet chimneyFanSpeedSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanSpeedSet chimneyFanSpeedSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStartTempGet chimneyFanStartTempGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStartTempGet chimneyFanStartTempGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStartTempReport chimneyFanStartTempReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStartTempReport chimneyFanStartTempReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStartTempSet chimneyFanStartTempSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStartTempSet chimneyFanStartTempSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStateGet chimneyFanStateGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStateGet chimneyFanStateGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStateReport chimneyFanStateReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStateReport chimneyFanStateReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStateSet chimneyFanStateSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStateSet chimneyFanStateSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStatusGet chimneyFanStatusGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStatusGet chimneyFanStatusGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStatusReport chimneyFanStatusReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStatusReport chimneyFanStatusReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTempGet chimneyFanStopTempGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTempGet chimneyFanStopTempGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTempReport chimneyFanStopTempReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTempReport chimneyFanStopTempReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTempSet chimneyFanStopTempSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTempSet chimneyFanStopTempSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTimeGet chimneyFanStopTimeGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTimeGet chimneyFanStopTimeGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTimeReport chimneyFanStopTimeReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTimeReport chimneyFanStopTimeReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTimeSet chimneyFanStopTimeSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.chimneyfanv1.ChimneyFanStopTimeSet chimneyFanStopTimeSet(java.util.Map a)
}
