package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait IrrigationV1 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemConfigGet irrigationSystemConfigGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemConfigGet irrigationSystemConfigGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemConfigReport irrigationSystemConfigReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemConfigReport irrigationSystemConfigReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemConfigSet irrigationSystemConfigSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemConfigSet irrigationSystemConfigSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemInfoGet irrigationSystemInfoGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemInfoGet irrigationSystemInfoGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemInfoReport irrigationSystemInfoReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemInfoReport irrigationSystemInfoReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemShutoff irrigationSystemShutoff()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemShutoff irrigationSystemShutoff(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemStatusGet irrigationSystemStatusGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemStatusGet irrigationSystemStatusGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemStatusReport irrigationSystemStatusReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationSystemStatusReport irrigationSystemStatusReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveConfigGet irrigationValveConfigGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveConfigGet irrigationValveConfigGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveConfigReport irrigationValveConfigReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveConfigReport irrigationValveConfigReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveConfigSet irrigationValveConfigSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveConfigSet irrigationValveConfigSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveInfoGet irrigationValveInfoGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveInfoGet irrigationValveInfoGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveInfoReport irrigationValveInfoReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveInfoReport irrigationValveInfoReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveRun irrigationValveRun()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveRun irrigationValveRun(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableGet irrigationValveTableGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableGet irrigationValveTableGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableReport irrigationValveTableReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableReport irrigationValveTableReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableRun irrigationValveTableRun()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableRun irrigationValveTableRun(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableSet irrigationValveTableSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1.IrrigationValveTableSet irrigationValveTableSet(java.util.Map a)
}
