package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait MeterTblMonitorV2 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblCurrentDataGet meterTblCurrentDataGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblCurrentDataGet meterTblCurrentDataGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblCurrentDataReport meterTblCurrentDataReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblCurrentDataReport meterTblCurrentDataReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblHistoricalDataGet meterTblHistoricalDataGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblHistoricalDataGet meterTblHistoricalDataGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblHistoricalDataReport meterTblHistoricalDataReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblHistoricalDataReport meterTblHistoricalDataReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblReport meterTblReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblReport meterTblReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusDateGet meterTblStatusDateGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusDateGet meterTblStatusDateGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusDepthGet meterTblStatusDepthGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusDepthGet meterTblStatusDepthGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusReport meterTblStatusReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusReport meterTblStatusReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusSupportedGet meterTblStatusSupportedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusSupportedGet meterTblStatusSupportedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusSupportedReport meterTblStatusSupportedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblStatusSupportedReport meterTblStatusSupportedReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTableCapabilityGet meterTblTableCapabilityGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTableCapabilityGet meterTblTableCapabilityGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTableIdGet meterTblTableIdGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTableIdGet meterTblTableIdGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTableIdReport meterTblTableIdReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTableIdReport meterTblTableIdReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTablePointAdmNoGet meterTblTablePointAdmNoGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTablePointAdmNoGet meterTblTablePointAdmNoGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTablePointAdmNoReport meterTblTablePointAdmNoReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv2.MeterTblTablePointAdmNoReport meterTblTablePointAdmNoReport(java.util.Map a)
}
