package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait MeterTblMonitorV1 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblCurrentDataGet meterTblCurrentDataGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblCurrentDataGet meterTblCurrentDataGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblCurrentDataReport meterTblCurrentDataReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblCurrentDataReport meterTblCurrentDataReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblHistoricalDataGet meterTblHistoricalDataGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblHistoricalDataGet meterTblHistoricalDataGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblHistoricalDataReport meterTblHistoricalDataReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblHistoricalDataReport meterTblHistoricalDataReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblReport meterTblReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblReport meterTblReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusDateGet meterTblStatusDateGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusDateGet meterTblStatusDateGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusDepthGet meterTblStatusDepthGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusDepthGet meterTblStatusDepthGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusReport meterTblStatusReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusReport meterTblStatusReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusSupportedGet meterTblStatusSupportedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusSupportedGet meterTblStatusSupportedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusSupportedReport meterTblStatusSupportedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblStatusSupportedReport meterTblStatusSupportedReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTableCapabilityGet meterTblTableCapabilityGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTableCapabilityGet meterTblTableCapabilityGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTableIdGet meterTblTableIdGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTableIdGet meterTblTableIdGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTableIdReport meterTblTableIdReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTableIdReport meterTblTableIdReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTablePointAdmNoGet meterTblTablePointAdmNoGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTablePointAdmNoGet meterTblTablePointAdmNoGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTablePointAdmNoReport meterTblTablePointAdmNoReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1.MeterTblTablePointAdmNoReport meterTblTablePointAdmNoReport(java.util.Map a)
}
