package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait ProtectionV2 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionEcGet protectionEcGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionEcGet protectionEcGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionEcReport protectionEcReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionEcReport protectionEcReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionEcSet protectionEcSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionEcSet protectionEcSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionGet protectionGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionGet protectionGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionReport protectionReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionReport protectionReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionSet protectionSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionSet protectionSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionSupportedGet protectionSupportedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionSupportedGet protectionSupportedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionSupportedReport protectionSupportedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionSupportedReport protectionSupportedReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionTimeoutGet protectionTimeoutGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionTimeoutGet protectionTimeoutGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionTimeoutReport protectionTimeoutReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionTimeoutReport protectionTimeoutReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionTimeoutSet protectionTimeoutSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.protectionv2.ProtectionTimeoutSet protectionTimeoutSet(java.util.Map a)
}
