package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait ScheduleEntryLockV2 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockEnableAllSet scheduleEntryLockEnableAllSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockEnableAllSet scheduleEntryLockEnableAllSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockEnableSet scheduleEntryLockEnableSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockEnableSet scheduleEntryLockEnableSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockTimeOffsetGet scheduleEntryLockTimeOffsetGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockTimeOffsetGet scheduleEntryLockTimeOffsetGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockTimeOffsetReport scheduleEntryLockTimeOffsetReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockTimeOffsetReport scheduleEntryLockTimeOffsetReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockTimeOffsetSet scheduleEntryLockTimeOffsetSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockTimeOffsetSet scheduleEntryLockTimeOffsetSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockWeekDayGet scheduleEntryLockWeekDayGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockWeekDayGet scheduleEntryLockWeekDayGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockWeekDayReport scheduleEntryLockWeekDayReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockWeekDayReport scheduleEntryLockWeekDayReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockWeekDaySet scheduleEntryLockWeekDaySet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockWeekDaySet scheduleEntryLockWeekDaySet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockYearDayGet scheduleEntryLockYearDayGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockYearDayGet scheduleEntryLockYearDayGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockYearDayReport scheduleEntryLockYearDayReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockYearDayReport scheduleEntryLockYearDayReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockYearDaySet scheduleEntryLockYearDaySet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryLockYearDaySet scheduleEntryLockYearDaySet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryTypeSupportedGet scheduleEntryTypeSupportedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryTypeSupportedGet scheduleEntryTypeSupportedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryTypeSupportedReport scheduleEntryTypeSupportedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv2.ScheduleEntryTypeSupportedReport scheduleEntryTypeSupportedReport(java.util.Map a)
}
