package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait ScheduleEntryLockV3 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockDailyRepeatingGet scheduleEntryLockDailyRepeatingGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockDailyRepeatingGet scheduleEntryLockDailyRepeatingGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockDailyRepeatingReport scheduleEntryLockDailyRepeatingReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockDailyRepeatingReport scheduleEntryLockDailyRepeatingReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockDailyRepeatingSet scheduleEntryLockDailyRepeatingSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockDailyRepeatingSet scheduleEntryLockDailyRepeatingSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockEnableAllSet scheduleEntryLockEnableAllSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockEnableAllSet scheduleEntryLockEnableAllSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockEnableSet scheduleEntryLockEnableSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockEnableSet scheduleEntryLockEnableSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockTimeOffsetGet scheduleEntryLockTimeOffsetGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockTimeOffsetGet scheduleEntryLockTimeOffsetGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockTimeOffsetReport scheduleEntryLockTimeOffsetReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockTimeOffsetReport scheduleEntryLockTimeOffsetReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockTimeOffsetSet scheduleEntryLockTimeOffsetSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockTimeOffsetSet scheduleEntryLockTimeOffsetSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockWeekDayGet scheduleEntryLockWeekDayGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockWeekDayGet scheduleEntryLockWeekDayGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockWeekDayReport scheduleEntryLockWeekDayReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockWeekDayReport scheduleEntryLockWeekDayReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockWeekDaySet scheduleEntryLockWeekDaySet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockWeekDaySet scheduleEntryLockWeekDaySet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockYearDayGet scheduleEntryLockYearDayGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockYearDayGet scheduleEntryLockYearDayGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockYearDayReport scheduleEntryLockYearDayReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockYearDayReport scheduleEntryLockYearDayReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockYearDaySet scheduleEntryLockYearDaySet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryLockYearDaySet scheduleEntryLockYearDaySet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryTypeSupportedGet scheduleEntryTypeSupportedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryTypeSupportedGet scheduleEntryTypeSupportedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryTypeSupportedReport scheduleEntryTypeSupportedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.scheduleentrylockv3.ScheduleEntryTypeSupportedReport scheduleEntryTypeSupportedReport(java.util.Map a)
}
