package me.biocomp.hubitat_ci.api.device_api.zwave.commandclasses

trait Security2V1 {
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexFail kexFail()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexFail kexFail(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexGet kexGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexGet kexGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexReport kexReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexReport kexReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexSet kexSet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.KexSet kexSet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.PublicKeyReport publicKeyReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.PublicKeyReport publicKeyReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2CommandsSupportedGet security2CommandsSupportedGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2CommandsSupportedGet security2CommandsSupportedGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2CommandsSupportedReport security2CommandsSupportedReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2CommandsSupportedReport security2CommandsSupportedReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2MessageEncapsulation security2MessageEncapsulation()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2MessageEncapsulation security2MessageEncapsulation(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NetworkKeyGet security2NetworkKeyGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NetworkKeyGet security2NetworkKeyGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NetworkKeyReport security2NetworkKeyReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NetworkKeyReport security2NetworkKeyReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NetworkKeyVerify security2NetworkKeyVerify()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NetworkKeyVerify security2NetworkKeyVerify(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NonceGet security2NonceGet()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NonceGet security2NonceGet(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NonceReport security2NonceReport()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2NonceReport security2NonceReport(java.util.Map a)
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2TransferEnd security2TransferEnd()
    abstract me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1.Security2TransferEnd security2TransferEnd(java.util.Map a)
}
