# strategy:
#   matrix:
#     linux:
#       imageName: "ubuntu-16.04"
#     mac:
#       imageName: "macos-10.13"
#     windows:
#       imageName: "vs2017-win2016"
#   maxParallel: 3

# pool:
#   vmImage: $(imageName)
#   demands: java

pool:
  vmImage: "vs2017-win2016"
  demands: java

trigger:
    [master]

steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  submodules: true

- task: Gradle@2
  displayName: 'gradlew build groovydoc'
  inputs:
    tasks: 'build groovydoc'
    pmdRunAnalysis: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'