name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyy_MM_dd)$(Rev:.r)
trigger: none # For manual publishing

jobs:
- deployment: DeployMavenPackage
  displayName: "Deploy Maven package"
  pool:
    name: "default"
    demands: java

  environment: 'hubitat_ci-dev'

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'src'
          submodules: true
        
        - task: Gradle@2
          displayName: '"gradlew build groovydoc publish" from src'
          inputs:
            tasks: build groovydoc publish

