name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyy_MM_dd)$(Rev:.r)
trigger: none # For manual publishing

jobs:
- deployment: DeployMavenPackage
  displayName: "Deploy Maven package"
  pool:
    name: "default"
    demands: java

  environment: 'hubitat_ci-dev'

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: src
        - task: DownloadPipelineArtifact@2
          inputs:
            source: 'specific'
            project: 'a3585777-7a80-4913-a4a1-c5184356a4b3' # You can get project GUID via this call: https://dev.azure.com/{Your org name}/_apis/projects?api-version=5.0
            pipeline: 10 # You can see this in URL of your pipeline
            targetPath: 'BuildResults'
            runVersion: 'latest'

        - task: CopyFiles@2
          displayName: 'Place build results to root'
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/src'
            Contents: |
              gradle/**
              gradle*
              build.gradle
            TargetFolder: '$(Pipeline.Workspace)'

        - task: CopyFiles@2
          displayName: 'Copy relevant gradle files to root'
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/BuildResults/drop'
            TargetFolder: '$(Pipeline.Workspace)'
        
        - task: Gradle@2
          displayName: '"gradlew publish" from root'
          inputs:
            tasks: publish
            workingDirectory: '$(Pipeline.Workspace)'

