name: $(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyy_MM_dd)$(Rev:.r)

trigger: none # Not running for commits. This is to be run manually.
pr: none # Not running for PRs.

jobs:
- deployment: DeployMavenPackage
  displayName: "Deploy Maven package"
  pool:
    name: "vs2017-win2016"
    demands: java

  environment: 'hubitat_ci-dev'

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          submodules: true

        - task: Gradle@2
          displayName: 'gradlew build groovydoc publish'
          inputs:
            tasks: build groovydoc publish

