package me.biocomp.hubitat_ci.api.helper

trait ReadableUTCDate {
    abstract long UTC(int a, int b, int c, int d, int e, int f)
    abstract boolean after(java.util.Date a)
    abstract boolean before(java.util.Date a)
    abstract int compareTo(java.lang.Object a)
    abstract int compareTo(java.util.Date a)
    abstract java.util.Date from(java.time.Instant a)
    abstract int getDate()
    abstract int getDay()
    abstract int getHours()
    abstract int getMinutes()
    abstract int getMonth()
    abstract int getSeconds()
    abstract long getTime()
    abstract int getTimezoneOffset()
    abstract int getYear()
    abstract long parse(java.lang.String a)
    abstract void setDate(int a)
    abstract void setHours(int a)
    abstract void setMinutes(int a)
    abstract void setMonth(int a)
    abstract void setSeconds(int a)
    abstract void setTime(long a)
    abstract void setYear(int a)
    abstract java.lang.String toGMTString()
    abstract java.time.Instant toInstant()
    abstract java.lang.String toLocaleString()
}
