package me.biocomp.hubitat_ci.api.device_api.zwave.commands.thermostatoperatingstatev2

trait ThermostatOperatingLoggingSupportedReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getAuxHeating()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getCooling()
    abstract java.lang.Boolean getFanOnly()
    abstract java.lang.Boolean getHeating()
    abstract java.lang.Boolean getIdle()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getPendingCool()
    abstract java.lang.Boolean getPendingHeat()
    abstract java.lang.Boolean getSecondStageCooling()
    abstract java.lang.Boolean getSecondStageHeating()
    abstract java.lang.Boolean getVenteconomizer()
    abstract void setAuxHeating(java.lang.Boolean a)
    abstract void setCooling(java.lang.Boolean a)
    abstract void setFanOnly(java.lang.Boolean a)
    abstract void setHeating(java.lang.Boolean a)
    abstract void setIdle(java.lang.Boolean a)
    abstract void setPendingCool(java.lang.Boolean a)
    abstract void setPendingHeat(java.lang.Boolean a)
    abstract void setSecondStageCooling(java.lang.Boolean a)
    abstract void setSecondStageHeating(java.lang.Boolean a)
    abstract void setVenteconomizer(java.lang.Boolean a)
}
