package me.biocomp.hubitat_ci.api.device_api.zwave.commands.notificationv3

import me.biocomp.hubitat_ci.api.device_api.zwave.Command

trait NotificationReport extends Command{
    abstract java.lang.Short getEvent() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getEvent()
    abstract java.util.List getEventParameter() // Original: public java.util.List hubitat.zwave.commands.notificationv3.NotificationReport.getEventParameter()
    abstract java.lang.Short getEventParametersLength() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getEventParametersLength()
    abstract java.lang.Short getNOTIFICATION_TYPE_ACCESS_CONTROL() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_ACCESS_CONTROL()
    abstract java.lang.Short getNOTIFICATION_TYPE_BURGLAR() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_BURGLAR()
    abstract java.lang.Short getNOTIFICATION_TYPE_CLOCK() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_CLOCK()
    abstract java.lang.Short getNOTIFICATION_TYPE_CO() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_CO()
    abstract java.lang.Short getNOTIFICATION_TYPE_CO2() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_CO2()
    abstract java.lang.Short getNOTIFICATION_TYPE_EMERGENCY() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_EMERGENCY()
    abstract java.lang.Short getNOTIFICATION_TYPE_FIRST() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_FIRST()
    abstract java.lang.Short getNOTIFICATION_TYPE_HEAT() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_HEAT()
    abstract java.lang.Short getNOTIFICATION_TYPE_POWER_MANAGEMENT() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_POWER_MANAGEMENT()
    abstract java.lang.Short getNOTIFICATION_TYPE_RESERVED0() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_RESERVED0()
    abstract java.lang.Short getNOTIFICATION_TYPE_SMOKE() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_SMOKE()
    abstract java.lang.Short getNOTIFICATION_TYPE_SYSTEM() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_SYSTEM()
    abstract java.lang.Short getNOTIFICATION_TYPE_WATER() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNOTIFICATION_TYPE_WATER()
    abstract java.lang.Short getNotificationStatus() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNotificationStatus()
    abstract java.lang.Short getNotificationType() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getNotificationType()
    abstract java.lang.Short getReserved() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getReserved()
    abstract java.lang.Boolean getSequence() // Original: public java.lang.Boolean hubitat.zwave.commands.notificationv3.NotificationReport.getSequence()
    abstract java.lang.Short getV1AlarmLevel() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getV1AlarmLevel()
    abstract java.lang.Short getV1AlarmType() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationReport.getV1AlarmType()
    abstract void setEvent(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setEvent(java.lang.Short)
    abstract void setEventParameter(java.util.List a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setEventParameter(java.util.List)
    abstract void setEventParametersLength(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setEventParametersLength(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_ACCESS_CONTROL(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_ACCESS_CONTROL(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_BURGLAR(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_BURGLAR(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_CLOCK(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_CLOCK(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_CO(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_CO(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_CO2(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_CO2(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_EMERGENCY(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_EMERGENCY(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_FIRST(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_FIRST(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_HEAT(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_HEAT(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_POWER_MANAGEMENT(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_POWER_MANAGEMENT(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_RESERVED0(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_RESERVED0(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_SMOKE(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_SMOKE(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_SYSTEM(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_SYSTEM(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_WATER(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationReport.setNOTIFICATION_TYPE_WATER(java.lang.Short)
    abstract void setNotificationStatus(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setNotificationStatus(java.lang.Short)
    abstract void setNotificationType(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setNotificationType(java.lang.Short)
    abstract void setReserved(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setReserved(java.lang.Short)
    abstract void setSequence(java.lang.Boolean a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setSequence(java.lang.Boolean)
    abstract void setV1AlarmLevel(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setV1AlarmLevel(java.lang.Short)
    abstract void setV1AlarmType(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationReport.setV1AlarmType(java.lang.Short)
}
