package me.biocomp.hubitat_ci.api.device_api.zwave.commands.batteryv3

trait BatteryReport {
    abstract java.lang.String format()
    abstract short getBATTERY_LOW_WARNING()
    abstract java.lang.Boolean getBackupBattery()
    abstract java.lang.Short getBatteryLevel()
    abstract short getCHARGING_STATUS_CHARGING()
    abstract short getCHARGING_STATUS_DISCHARGING()
    abstract short getCHARGING_STATUS_MAINTAINING()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getChargingStatus()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getDisconnected()
    abstract java.lang.Boolean getLowFluid()
    abstract java.lang.Boolean getLowTemperatureStatus()
    abstract java.lang.Boolean getOverheating()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getRechargeable()
    abstract java.lang.Short getReplaceRecharge()
    abstract void setBackupBattery(java.lang.Boolean a)
    abstract void setBatteryLevel(java.lang.Short a)
    abstract void setChargingStatus(java.lang.Short a)
    abstract void setDisconnected(java.lang.Boolean a)
    abstract void setLowFluid(java.lang.Boolean a)
    abstract void setLowTemperatureStatus(java.lang.Boolean a)
    abstract void setOverheating(java.lang.Boolean a)
    abstract void setRechargeable(java.lang.Boolean a)
    abstract void setReplaceRecharge(java.lang.Short a)
}
