package me.biocomp.hubitat_ci.api.device_api.zwave.commands.timev2

trait TimeOffsetSet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getDayEndDst()
    abstract java.lang.Short getDayStartDst()
    abstract java.lang.Short getHourEndDst()
    abstract java.lang.Short getHourStartDst()
    abstract java.lang.Short getHourTzo()
    abstract java.lang.Short getMinuteOffsetDst()
    abstract java.lang.Short getMinuteTzo()
    abstract java.lang.Short getMonthEndDst()
    abstract java.lang.Short getMonthStartDst()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSignOffsetDst()
    abstract java.lang.Short getSignTzo()
    abstract void setDayEndDst(java.lang.Short a)
    abstract void setDayStartDst(java.lang.Short a)
    abstract void setHourEndDst(java.lang.Short a)
    abstract void setHourStartDst(java.lang.Short a)
    abstract void setHourTzo(java.lang.Short a)
    abstract void setMinuteOffsetDst(java.lang.Short a)
    abstract void setMinuteTzo(java.lang.Short a)
    abstract void setMonthEndDst(java.lang.Short a)
    abstract void setMonthStartDst(java.lang.Short a)
    abstract void setSignOffsetDst(java.lang.Short a)
    abstract void setSignTzo(java.lang.Short a)
}
