package me.biocomp.hubitat_ci.api.device_api.zigbee

trait SmartShield {
    abstract int getClusterId()
    abstract int getCommand()
    abstract List getData()
    abstract int getDestinationEndpoint()
    abstract int getDirection()
    abstract boolean getIsClusterSpecific()
    abstract boolean getIsManufacturerSpecific()
    abstract int getManufacturerId()
    abstract int getMessageType()
    abstract Integer getNumber()
    abstract int getOptions()
    abstract int getProfileId()
    abstract int getSenderShortId()
    abstract int getSourceEndpoint()
    abstract String getText()
    abstract boolean isIsClusterSpecific()
    abstract boolean isIsManufacturerSpecific()
    abstract SmartShield populateFromCatchall(Map catchAll)
    abstract SmartShield populateFromReadAttribute(Map attributes)
    abstract void setClusterId(int clusterId)
    abstract void setCommand(int command)
    abstract void setData(List data)
    abstract void setDestinationEndpoint(int destinationEndpoint)
    abstract void setDirection(int direction)
    abstract void setIsClusterSpecific(boolean isClusterSpecific)
    abstract void setIsManufacturerSpecific(boolean isManufacturerSpecific)
    abstract void setManufacturerId(int manufacturerId)
    abstract void setMessageType(int messageType)
    abstract void setNumber(int number)
    abstract void setOptions(int options)
    abstract void setProfileId(int profileId)
    abstract void setSenderShortId(int senderShortId)
    abstract void setSourceEndpoint(int sourceEndpoint)
    abstract void setText(String text)
}
