package me.biocomp.hubitat_ci.api.device_api.zwave.commands.indicatorv2

trait IndicatorSupportedReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getBinary()
    abstract java.lang.Short getBitMaskLength()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED_ZONE_1()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED_ZONE_2()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED_ZONE_3()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED_ZONE_4()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED_ZONE_5()
    abstract java.lang.Short getINDICATOR_TYPE_ARMED_ZONE_6()
    abstract java.lang.Short getINDICATOR_TYPE_BACKLIGHT_COMMANDS()
    abstract java.lang.Short getINDICATOR_TYPE_BACKLIGHT_DIGITS()
    abstract java.lang.Short getINDICATOR_TYPE_BACKLIGHT_LCD()
    abstract java.lang.Short getINDICATOR_TYPE_BACKLIGHT_LETTERS()
    abstract java.lang.Short getINDICATOR_TYPE_BUSY()
    abstract java.lang.Short getINDICATOR_TYPE_BUZZER()
    abstract java.lang.Short getINDICATOR_TYPE_CODE_ACCEPTED()
    abstract java.lang.Short getINDICATOR_TYPE_CODE_REJECTED()
    abstract java.lang.Short getINDICATOR_TYPE_DISARMED()
    abstract java.lang.Short getINDICATOR_TYPE_ENTER_ID()
    abstract java.lang.Short getINDICATOR_TYPE_ENTER_PIN()
    abstract java.lang.Short getINDICATOR_TYPE_FAULT()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_1()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_10()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_11()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_12()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_2()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_3()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_4()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_5()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_6()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_7()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_8()
    abstract java.lang.Short getINDICATOR_TYPE_INDICATION_BUTTON_9()
    abstract java.lang.Short getINDICATOR_TYPE_READY()
    abstract java.lang.Short getINDICATOR_TYPE_RESERVED()
    abstract java.lang.Short getIndicatorId()
    abstract java.lang.Boolean getLowPower()
    abstract java.lang.Boolean getMultiLevel()
    abstract java.lang.Short getNextIndicatorId()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getTogglingCycles()
    abstract java.lang.Boolean getTogglingPeriods()
    abstract void setBinary(java.lang.Boolean a)
    abstract void setBitMaskLength(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED_ZONE_1(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED_ZONE_2(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED_ZONE_3(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED_ZONE_4(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED_ZONE_5(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ARMED_ZONE_6(java.lang.Short a)
    abstract void setINDICATOR_TYPE_BACKLIGHT_COMMANDS(java.lang.Short a)
    abstract void setINDICATOR_TYPE_BACKLIGHT_DIGITS(java.lang.Short a)
    abstract void setINDICATOR_TYPE_BACKLIGHT_LCD(java.lang.Short a)
    abstract void setINDICATOR_TYPE_BACKLIGHT_LETTERS(java.lang.Short a)
    abstract void setINDICATOR_TYPE_BUSY(java.lang.Short a)
    abstract void setINDICATOR_TYPE_BUZZER(java.lang.Short a)
    abstract void setINDICATOR_TYPE_CODE_ACCEPTED(java.lang.Short a)
    abstract void setINDICATOR_TYPE_CODE_REJECTED(java.lang.Short a)
    abstract void setINDICATOR_TYPE_DISARMED(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ENTER_ID(java.lang.Short a)
    abstract void setINDICATOR_TYPE_ENTER_PIN(java.lang.Short a)
    abstract void setINDICATOR_TYPE_FAULT(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_1(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_10(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_11(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_12(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_2(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_3(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_4(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_5(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_6(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_7(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_8(java.lang.Short a)
    abstract void setINDICATOR_TYPE_INDICATION_BUTTON_9(java.lang.Short a)
    abstract void setINDICATOR_TYPE_READY(java.lang.Short a)
    abstract void setINDICATOR_TYPE_RESERVED(java.lang.Short a)
    abstract void setIndicatorId(java.lang.Short a)
    abstract void setLowPower(java.lang.Boolean a)
    abstract void setMultiLevel(java.lang.Boolean a)
    abstract void setNextIndicatorId(java.lang.Short a)
    abstract void setTogglingCycles(java.lang.Boolean a)
    abstract void setTogglingPeriods(java.lang.Boolean a)
}
