package me.biocomp.hubitat_ci.api.hub.domain

trait InstalledApp {
    abstract void addModeRestriction(java.lang.Long a)
    abstract me.biocomp.hubitat_ci.api.common_api.AppType getAppType()
    abstract java.lang.Long getAppTypeId()
    abstract boolean getDisabled()
    abstract java.lang.Long getId()
    abstract boolean getInstalled()
    abstract java.lang.String getLabel()
    abstract java.lang.String getName()
    abstract java.lang.Long getParentAppId()
    abstract java.util.List getRestrictedModes()
    abstract java.lang.String getTrueLabel()
    abstract java.lang.Long getVersion()
    abstract boolean isDisabled()
    abstract boolean isInstalled()
    abstract void setAppType(me.biocomp.hubitat_ci.api.common_api.AppType a)
    abstract void setAppTypeId(java.lang.Long a)
    abstract void setDisabled(boolean a)
    abstract void setId(java.lang.Long a)
    abstract void setInstalled(boolean a)
    abstract void setLabel(java.lang.String a)
    abstract void setName(java.lang.String a)
    abstract void setParentAppId(java.lang.Long a)
    abstract void setRestrictedModes(java.util.List a)
    abstract void setVersion(java.lang.Long a)
    abstract void updateLabel(java.lang.String a)
}
