package me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1

trait MeterTblHistoricalDataGet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Integer getHistoricalDatasetRequested()
    abstract java.lang.Short getMaximumReports()
    abstract java.util.List getPayload()
    abstract java.lang.Short getStartDay()
    abstract java.lang.Short getStartHourLocalTime()
    abstract java.lang.Short getStartMinuteLocalTime()
    abstract java.lang.Short getStartMonth()
    abstract java.lang.Short getStartSecondLocalTime()
    abstract java.lang.Integer getStartYear()
    abstract java.lang.Short getStopDay()
    abstract java.lang.Short getStopHourLocalTime()
    abstract java.lang.Short getStopMinuteLocalTime()
    abstract java.lang.Short getStopMonth()
    abstract java.lang.Short getStopSecondLocalTime()
    abstract java.lang.Integer getStopYear()
    abstract void setHistoricalDatasetRequested(java.lang.Integer a)
    abstract void setMaximumReports(java.lang.Short a)
    abstract void setStartDay(java.lang.Short a)
    abstract void setStartHourLocalTime(java.lang.Short a)
    abstract void setStartMinuteLocalTime(java.lang.Short a)
    abstract void setStartMonth(java.lang.Short a)
    abstract void setStartSecondLocalTime(java.lang.Short a)
    abstract void setStartYear(java.lang.Integer a)
    abstract void setStopDay(java.lang.Short a)
    abstract void setStopHourLocalTime(java.lang.Short a)
    abstract void setStopMinuteLocalTime(java.lang.Short a)
    abstract void setStopMonth(java.lang.Short a)
    abstract void setStopSecondLocalTime(java.lang.Short a)
    abstract void setStopYear(java.lang.Integer a)
}
