package me.biocomp.hubitat_ci.api.device_api.zwave.commands.metertblmonitorv1

trait MeterTblReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Integer getDataHistorySupported()
    abstract java.lang.Integer getDatasetHistorySupported()
    abstract java.lang.Integer getDatasetSupported()
    abstract java.lang.Short getMeterType()
    abstract java.lang.Short getPAY_METER_CREDITMETER()
    abstract java.lang.Short getPAY_METER_PREPAYMENT_METER()
    abstract java.lang.Short getPAY_METER_PREPAYMENT_METER_DEBT()
    abstract java.lang.Short getPAY_METER_RESERVED0()
    abstract java.lang.Short getPayMeter()
    abstract java.util.List getPayload()
    abstract java.lang.Short getRateType()
    abstract void setDataHistorySupported(java.lang.Integer a)
    abstract void setDatasetHistorySupported(java.lang.Integer a)
    abstract void setDatasetSupported(java.lang.Integer a)
    abstract void setMeterType(java.lang.Short a)
    abstract void setPAY_METER_CREDITMETER(java.lang.Short a)
    abstract void setPAY_METER_PREPAYMENT_METER(java.lang.Short a)
    abstract void setPAY_METER_PREPAYMENT_METER_DEBT(java.lang.Short a)
    abstract void setPAY_METER_RESERVED0(java.lang.Short a)
    abstract void setPayMeter(java.lang.Short a)
    abstract void setRateType(java.lang.Short a)
}
