package me.biocomp.hubitat_ci.api.device_api.zwave.commands.security2v1

trait KexFail {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getFailType()
    abstract java.lang.Short getKEX_FAIL_AUTH()
    abstract java.lang.Short getKEX_FAIL_CANCEL()
    abstract java.lang.Short getKEX_FAIL_DECRYPT()
    abstract java.lang.Short getKEX_FAIL_KEX_CURVES()
    abstract java.lang.Short getKEX_FAIL_KEX_KEY()
    abstract java.lang.Short getKEX_FAIL_KEX_SCHEME()
    abstract java.lang.Short getKEX_FAIL_KEY_GET()
    abstract java.lang.Short getKEX_FAIL_KEY_REPORT()
    abstract java.lang.Short getKEX_FAIL_KEY_VERIFY()
    abstract java.util.List getPayload()
    abstract void setFailType(java.lang.Short a)
    abstract void setKEX_FAIL_AUTH(java.lang.Short a)
    abstract void setKEX_FAIL_CANCEL(java.lang.Short a)
    abstract void setKEX_FAIL_DECRYPT(java.lang.Short a)
    abstract void setKEX_FAIL_KEX_CURVES(java.lang.Short a)
    abstract void setKEX_FAIL_KEX_KEY(java.lang.Short a)
    abstract void setKEX_FAIL_KEX_SCHEME(java.lang.Short a)
    abstract void setKEX_FAIL_KEY_GET(java.lang.Short a)
    abstract void setKEX_FAIL_KEY_REPORT(java.lang.Short a)
    abstract void setKEX_FAIL_KEY_VERIFY(java.lang.Short a)
}
