package me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1

trait IrrigationValveConfigSet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getFlowHighThresholdPrecision()
    abstract java.lang.Short getFlowHighThresholdScale()
    abstract java.lang.Short getFlowHighThresholdSize()
    abstract java.util.List getFlowHighThresholdValue()
    abstract java.lang.Short getFlowLowThresholdPrecision()
    abstract java.lang.Short getFlowLowThresholdScale()
    abstract java.lang.Short getFlowLowThresholdSize()
    abstract java.util.List getFlowLowThresholdValue()
    abstract java.lang.Boolean getMasterValve()
    abstract java.lang.Short getMaximumFlowPrecision()
    abstract java.lang.Short getMaximumFlowScale()
    abstract java.lang.Short getMaximumFlowSize()
    abstract java.util.List getMaximumFlowValue()
    abstract java.lang.Short getNominalCurrentHighThreshold()
    abstract java.lang.Short getNominalCurrentLowThreshold()
    abstract java.util.List getPayload()
    abstract short getSENSOR_USAGE_USE_MOISTURE_SENSOR()
    abstract short getSENSOR_USAGE_USE_RAIN_SENSOR()
    abstract java.math.BigDecimal getScaledFlowHighThreshold()
    abstract java.math.BigDecimal getScaledFlowLowThreshold()
    abstract java.math.BigDecimal getScaledMaximumFlow()
    abstract java.lang.Short getSensorUsage()
    abstract java.lang.Short getValveID()
    abstract void setFlowHighThresholdPrecision(java.lang.Short a)
    abstract void setFlowHighThresholdScale(java.lang.Short a)
    abstract void setFlowHighThresholdSize(java.lang.Short a)
    abstract void setFlowHighThresholdValue(java.util.List a)
    abstract void setFlowLowThresholdPrecision(java.lang.Short a)
    abstract void setFlowLowThresholdScale(java.lang.Short a)
    abstract void setFlowLowThresholdSize(java.lang.Short a)
    abstract void setFlowLowThresholdValue(java.util.List a)
    abstract void setMasterValve(java.lang.Boolean a)
    abstract void setMaximumFlowPrecision(java.lang.Short a)
    abstract void setMaximumFlowScale(java.lang.Short a)
    abstract void setMaximumFlowSize(java.lang.Short a)
    abstract void setMaximumFlowValue(java.util.List a)
    abstract void setNominalCurrentHighThreshold(java.lang.Short a)
    abstract void setNominalCurrentLowThreshold(java.lang.Short a)
    abstract void setScaledFlowHighThreshold(java.math.BigDecimal a)
    abstract void setScaledFlowLowThreshold(java.math.BigDecimal a)
    abstract void setScaledMaximumFlow(java.math.BigDecimal a)
    abstract void setSensorUsage(java.lang.Short a)
    abstract void setValveID(java.lang.Short a)
}
