package me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1

trait IrrigationSystemConfigSet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getHighPressureThresholdPrecision()
    abstract java.lang.Short getHighPressureThresholdScale()
    abstract java.lang.Short getHighPressureThresholdSize()
    abstract java.util.List getHighPressureThresholdValue()
    abstract java.lang.Short getLowPressureThresholdPrecision()
    abstract java.lang.Short getLowPressureThresholdScale()
    abstract java.lang.Short getLowPressureThresholdSize()
    abstract java.util.List getLowPressureThresholdValue()
    abstract java.lang.Short getMasterValveDelay()
    abstract java.util.List getPayload()
    abstract short getSENSOR_POLARITY_MOISTURE_SENSOR_POLARITY()
    abstract short getSENSOR_POLARITY_RAIN_SENSOR_POLARITY()
    abstract short getSENSOR_POLARITY_VALID()
    abstract java.math.BigDecimal getScaledHighPressureThreshold()
    abstract java.math.BigDecimal getScaledLowPressureThresholdPressure()
    abstract java.lang.Short getSensorPolarity()
    abstract void setHighPressureThresholdPrecision(java.lang.Short a)
    abstract void setHighPressureThresholdScale(java.lang.Short a)
    abstract void setHighPressureThresholdSize(java.lang.Short a)
    abstract void setHighPressureThresholdValue(java.util.List a)
    abstract void setLowPressureThresholdPrecision(java.lang.Short a)
    abstract void setLowPressureThresholdScale(java.lang.Short a)
    abstract void setLowPressureThresholdSize(java.lang.Short a)
    abstract void setLowPressureThresholdValue(java.util.List a)
    abstract void setMasterValveDelay(java.lang.Short a)
    abstract void setScaledHighPressureThreshold(java.math.BigDecimal a)
    abstract void setScaledLowPressureThresholdPressure(java.math.BigDecimal a)
    abstract void setSensorPolarity(java.lang.Short a)
}
