package me.biocomp.hubitat_ci.api.device_api.zwave.commands.irrigationv1

trait IrrigationSystemStatusReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract short getERROR_STATUS_EMERGENCY_SHUTDOWN()
    abstract short getERROR_STATUS_HIGH_THRESHOLD_TRIGGERED()
    abstract short getERROR_STATUS_LOW_THRESHOLD_TRIGGERED()
    abstract short getERROR_STATUS_NOT_PROGRAMMED()
    abstract short getERROR_STATUS_VALVE_ERRORS()
    abstract java.lang.Short getFlowPrecision()
    abstract java.lang.Short getFlowScale()
    abstract java.lang.Short getFlowSize()
    abstract java.util.List getFlowValue()
    abstract java.lang.Boolean getMasterValve()
    abstract java.util.List getPayload()
    abstract java.lang.Short getPressurePrecision()
    abstract java.lang.Short getPressureScale()
    abstract java.lang.Short getPressureSize()
    abstract java.util.List getPressureValue()
    abstract short getSTATUS_FLOW_SENSOR_DETECTED()
    abstract short getSTATUS_MOISTURE_SENSOR_DETECTED()
    abstract short getSTATUS_PRESSURE_SENSOR_DETECTED()
    abstract short getSTATUS_RAIN_SENSOR_DETECTED()
    abstract java.math.BigDecimal getScaledFlow()
    abstract java.math.BigDecimal getScaledPressure()
    abstract java.lang.Short getSensorStatus()
    abstract java.lang.Short getShutoffDuration()
    abstract java.lang.Short getSystemErrorStatus()
    abstract java.lang.Short getSystemVoltage()
    abstract java.lang.Short getValveID()
    abstract void setFlowPrecision(java.lang.Short a)
    abstract void setFlowScale(java.lang.Short a)
    abstract void setFlowSize(java.lang.Short a)
    abstract void setFlowValue(java.util.List a)
    abstract void setMasterValve(java.lang.Boolean a)
    abstract void setPressurePrecision(java.lang.Short a)
    abstract void setPressureScale(java.lang.Short a)
    abstract void setPressureSize(java.lang.Short a)
    abstract void setPressureValue(java.util.List a)
    abstract void setScaledFlow(java.math.BigDecimal a)
    abstract void setScaledPressure(java.math.BigDecimal a)
    abstract void setSensorStatus(java.lang.Short a)
    abstract void setShutoffDuration(java.lang.Short a)
    abstract void setSystemErrorStatus(java.lang.Short a)
    abstract void setSystemVoltage(java.lang.Short a)
    abstract void setValveID(java.lang.Short a)
}
