package me.biocomp.hubitat_ci.api.device_api.zwave.commands.hrvcontrolv1

trait HrvControlModeSupportedReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getDemandAutomatic()
    abstract java.lang.Boolean getEnergySavingsMode()
    abstract java.lang.Short getMANUAL_CONTROL_SUPPORTED_BYPASS_AUTO()
    abstract java.lang.Short getMANUAL_CONTROL_SUPPORTED_BYPASS_OPEN_CLOSE()
    abstract java.lang.Short getMANUAL_CONTROL_SUPPORTED_MODULATED_BYPASS()
    abstract java.lang.Short getMANUAL_CONTROL_SUPPORTED_VENTILATION_RATE()
    abstract java.lang.Boolean getManual()
    abstract java.lang.Short getManualControlSupported()
    abstract java.lang.Boolean getOff()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getSchedule()
    abstract void setDemandAutomatic(java.lang.Boolean a)
    abstract void setEnergySavingsMode(java.lang.Boolean a)
    abstract void setMANUAL_CONTROL_SUPPORTED_BYPASS_AUTO(java.lang.Short a)
    abstract void setMANUAL_CONTROL_SUPPORTED_BYPASS_OPEN_CLOSE(java.lang.Short a)
    abstract void setMANUAL_CONTROL_SUPPORTED_MODULATED_BYPASS(java.lang.Short a)
    abstract void setMANUAL_CONTROL_SUPPORTED_VENTILATION_RATE(java.lang.Short a)
    abstract void setManual(java.lang.Boolean a)
    abstract void setManualControlSupported(java.lang.Short a)
    abstract void setOff(java.lang.Boolean a)
    abstract void setSchedule(java.lang.Boolean a)
}
