package me.biocomp.hubitat_ci.api.device_api.zwave.commands.sensormultilevelv1

trait SensorMultilevelReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.util.List getPayload()
    abstract java.lang.Short getPrecision()
    abstract java.lang.Short getSENSOR_TYPE_GENERAL_PURPOSE_VALUE_VERSION_1()
    abstract java.lang.Short getSENSOR_TYPE_LUMINANCE_VERSION_1()
    abstract java.lang.Short getSENSOR_TYPE_TEMPERATURE_VERSION_1()
    abstract java.lang.Short getScale()
    abstract java.math.BigDecimal getScaledSensorValue()
    abstract java.lang.Short getSensorType()
    abstract java.util.List getSensorValue()
    abstract java.lang.Short getSize()
    abstract void setPrecision(java.lang.Short a)
    abstract void setSENSOR_TYPE_GENERAL_PURPOSE_VALUE_VERSION_1(java.lang.Short a)
    abstract void setSENSOR_TYPE_LUMINANCE_VERSION_1(java.lang.Short a)
    abstract void setSENSOR_TYPE_TEMPERATURE_VERSION_1(java.lang.Short a)
    abstract void setScale(java.lang.Short a)
    abstract void setScaledSensorValue(java.math.BigDecimal a)
    abstract void setSensorType(java.lang.Short a)
    abstract void setSensorValue(java.util.List a)
    abstract void setSize(java.lang.Short a)
}
