package me.biocomp.hubitat_ci.api.common_api

// com.hubitat.hub.domain.AppType
trait AppType {
    abstract java.lang.String getAppSettings() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getAppSettings()
    abstract java.lang.String getAuthor() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getAuthor()
    abstract java.lang.String getCategory() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getCategory()
    abstract java.lang.String getClassLocation() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getClassLocation()
    abstract java.util.Date getCreateTime() // Original: public java.util.Date com.hubitat.hub.domain.AppType.getCreateTime()
    abstract java.lang.String getDEPRECATED() // Original: public static java.lang.String com.hubitat.hub.domain.AppType.getDEPRECATED()
    abstract java.lang.String getDescription() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getDescription()
    abstract java.lang.String getDocumentationLink() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getDocumentationLink()
    abstract java.lang.String getIconUrl() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getIconUrl()
    abstract java.lang.String getIconX2Url() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getIconX2Url()
    abstract java.lang.String getIconX3Url() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getIconX3Url()
    abstract java.lang.Long getId() // Original: public java.lang.Long com.hubitat.hub.domain.AppType.getId()
    abstract boolean getInstallOnOpen() // Original: public boolean com.hubitat.hub.domain.AppType.getInstallOnOpen()
    abstract java.lang.String getName() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getName()
    abstract java.lang.String getNamespace() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getNamespace()
    abstract java.lang.String getOauthClientId() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getOauthClientId()
    abstract java.lang.String getOauthClientSecret() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getOauthClientSecret()
    abstract java.lang.String getOauthDisplayLink() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getOauthDisplayLink()
    abstract java.lang.String getOauthDisplayName() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getOauthDisplayName()
    abstract java.lang.Long getParentAppId() // Original: public java.lang.Long com.hubitat.hub.domain.AppType.getParentAppId()
    abstract java.lang.String getSYSTEM() // Original: public static java.lang.String com.hubitat.hub.domain.AppType.getSYSTEM()
    abstract boolean getSingleInstance() // Original: public boolean com.hubitat.hub.domain.AppType.getSingleInstance()
    abstract java.lang.Long getSingleInstanceInstalledId() // Original: public java.lang.Long com.hubitat.hub.domain.AppType.getSingleInstanceInstalledId()
    abstract java.lang.String getSource() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getSource()
    abstract java.lang.String getType() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getType()
    abstract java.lang.String getUSER() // Original: public static java.lang.String com.hubitat.hub.domain.AppType.getUSER()
    abstract java.util.Date getUpdateTime() // Original: public java.util.Date com.hubitat.hub.domain.AppType.getUpdateTime()
    abstract java.lang.Long getVersion() // Original: public java.lang.Long com.hubitat.hub.domain.AppType.getVersion()
    abstract java.lang.String getVideoLink() // Original: public java.lang.String com.hubitat.hub.domain.AppType.getVideoLink()
    abstract boolean isDeprecated() // Original: public boolean com.hubitat.hub.domain.AppType.isDeprecated()
    abstract boolean isInstallOnOpen() // Original: public boolean com.hubitat.hub.domain.AppType.isInstallOnOpen()
    abstract boolean isSetting() // Original: public boolean com.hubitat.hub.domain.AppType.isSetting()
    abstract boolean isSingleInstance() // Original: public boolean com.hubitat.hub.domain.AppType.isSingleInstance()
    abstract boolean isSystem() // Original: public boolean com.hubitat.hub.domain.AppType.isSystem()
    abstract boolean isUser() // Original: public boolean com.hubitat.hub.domain.AppType.isUser()
    abstract void setAppSettings(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setAppSettings(java.lang.String)
    abstract void setAuthor(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setAuthor(java.lang.String)
    abstract void setCategory(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setCategory(java.lang.String)
    abstract void setClassLocation(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setClassLocation(java.lang.String)
    abstract void setCreateTime(java.util.Date a) // Original: public void com.hubitat.hub.domain.AppType.setCreateTime(java.util.Date)
    abstract void setDescription(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setDescription(java.lang.String)
    abstract void setDocumentationLink(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setDocumentationLink(java.lang.String)
    abstract void setIconUrl(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setIconUrl(java.lang.String)
    abstract void setIconX2Url(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setIconX2Url(java.lang.String)
    abstract void setIconX3Url(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setIconX3Url(java.lang.String)
    abstract void setId(java.lang.Long a) // Original: public void com.hubitat.hub.domain.AppType.setId(java.lang.Long)
    abstract void setInstallOnOpen(boolean a) // Original: public void com.hubitat.hub.domain.AppType.setInstallOnOpen(boolean)
    abstract void setName(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setName(java.lang.String)
    abstract void setNamespace(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setNamespace(java.lang.String)
    abstract void setOauthClientId(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setOauthClientId(java.lang.String)
    abstract void setOauthClientSecret(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setOauthClientSecret(java.lang.String)
    abstract void setOauthDisplayLink(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setOauthDisplayLink(java.lang.String)
    abstract void setOauthDisplayName(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setOauthDisplayName(java.lang.String)
    abstract void setParentAppId(java.lang.Long a) // Original: public void com.hubitat.hub.domain.AppType.setParentAppId(java.lang.Long)
    abstract void setSingleInstance(boolean a) // Original: public void com.hubitat.hub.domain.AppType.setSingleInstance(boolean)
    abstract void setSingleInstanceInstalledId(java.lang.Long a) // Original: public void com.hubitat.hub.domain.AppType.setSingleInstanceInstalledId(java.lang.Long)
    abstract void setSource(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setSource(java.lang.String)
    abstract void setType(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setType(java.lang.String)
    abstract void setUpdateTime(java.util.Date a) // Original: public void com.hubitat.hub.domain.AppType.setUpdateTime(java.util.Date)
    abstract void setVersion(java.lang.Long a) // Original: public void com.hubitat.hub.domain.AppType.setVersion(java.lang.Long)
    abstract void setVideoLink(java.lang.String a) // Original: public void com.hubitat.hub.domain.AppType.setVideoLink(java.lang.String)
    abstract java.util.Map toMap() // Original: public java.util.Map com.hubitat.hub.domain.AppType.toMap()
}