package me.biocomp.hubitat_ci.api.common_api

interface Hub {
    abstract String getFirmwareVersionString()
    abstract Long getId()
    abstract String getLocalIP()
    abstract String getLocalSrvPortTCP()
    abstract String getName()
    abstract String getType()
    abstract String getZigbeeEui()
    abstract String getZigbeeId()

    abstract void addData(java.util.Map a) // Original: public void com.hubitat.hub.domain.Hub.addData(java.util.Map)
    abstract java.util.Date getCreateTime() // Original: public java.util.Date com.hubitat.hub.domain.Hub.getCreateTime()
    abstract java.util.Map getData() // Original: public java.util.Map com.hubitat.hub.domain.Hub.getData()
    abstract java.util.Map getDataSorted() // Original: public java.util.Map com.hubitat.hub.domain.Hub.getDataSorted()
    abstract java.lang.String getDataValue(java.lang.String a) // Original: public java.lang.String com.hubitat.hub.domain.Hub.getDataValue(java.lang.String)
    abstract java.lang.String getHardwareID() // Original: public java.lang.String com.hubitat.hub.domain.Hub.getHardwareID()
    abstract java.util.Date getLastActivityTime() // Original: public java.util.Date com.hubitat.hub.domain.Hub.getLastActivityTime()
    abstract java.lang.Long getLocationId() // Original: public java.lang.Long com.hubitat.hub.domain.Hub.getLocationId()
    abstract java.util.Date getUpdateTime() // Original: public java.util.Date com.hubitat.hub.domain.Hub.getUpdateTime()
    abstract java.math.BigInteger getUptime() // Original: public java.math.BigInteger com.hubitat.hub.domain.Hub.getUptime()
    abstract java.lang.Long getVersion() // Original: public java.lang.Long com.hubitat.hub.domain.Hub.getVersion()
    abstract java.lang.Boolean isBatteryInUse() // Original: public java.lang.Boolean com.hubitat.hub.domain.Hub.isBatteryInUse()
    abstract void setCreateTime(java.util.Date a) // Original: public void com.hubitat.hub.domain.Hub.setCreateTime(java.util.Date)
    abstract void setData(java.util.Map a) // Original: public void com.hubitat.hub.domain.Hub.setData(java.util.Map)
    abstract void setId(java.lang.Long a) // Original: public void com.hubitat.hub.domain.Hub.setId(java.lang.Long)
    abstract void setLastActivityTime(java.util.Date a) // Original: public void com.hubitat.hub.domain.Hub.setLastActivityTime(java.util.Date)
    abstract void setLocationId(java.lang.Long a) // Original: public void com.hubitat.hub.domain.Hub.setLocationId(java.lang.Long)
    abstract void setName(java.lang.String a) // Original: public void com.hubitat.hub.domain.Hub.setName(java.lang.String)
    abstract void setUpdateTime(java.util.Date a) // Original: public void com.hubitat.hub.domain.Hub.setUpdateTime(java.util.Date)
    abstract void setVersion(java.lang.Long a) // Original: public void com.hubitat.hub.domain.Hub.setVersion(java.lang.Long)
    abstract java.util.Map toMap() // Original: public java.util.Map com.hubitat.hub.domain.Hub.toMap()
    abstract boolean updateSystemTime(java.util.Date a) // Original: public static boolean com.hubitat.hub.domain.Hub.updateSystemTime(java.util.Date)
}

