package me.biocomp.hubitat_ci.api.device_api.zwave.commands.entrycontrolv1

trait EntryControlNotification {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getDATA_TYPE_ASCII()
    abstract java.lang.Short getDATA_TYPE_MD5()
    abstract java.lang.Short getDATA_TYPE_NA()
    abstract java.lang.Short getDATA_TYPE_RAW()
    abstract java.lang.Short getDataType()
    abstract java.lang.Short getEVENT_TYPE_ALERT_MEDICAL()
    abstract java.lang.Short getEVENT_TYPE_ALERT_PANIC()
    abstract java.lang.Short getEVENT_TYPE_ARM_1()
    abstract java.lang.Short getEVENT_TYPE_ARM_2()
    abstract java.lang.Short getEVENT_TYPE_ARM_3()
    abstract java.lang.Short getEVENT_TYPE_ARM_4()
    abstract java.lang.Short getEVENT_TYPE_ARM_5()
    abstract java.lang.Short getEVENT_TYPE_ARM_6()
    abstract java.lang.Short getEVENT_TYPE_ARM_ALL()
    abstract java.lang.Short getEVENT_TYPE_ARM_AWAY()
    abstract java.lang.Short getEVENT_TYPE_ARM_HOME()
    abstract java.lang.Short getEVENT_TYPE_BELL()
    abstract java.lang.Short getEVENT_TYPE_CACHED_KEYS()
    abstract java.lang.Short getEVENT_TYPE_CACHING()
    abstract java.lang.Short getEVENT_TYPE_CANCEL()
    abstract java.lang.Short getEVENT_TYPE_DISARM_ALL()
    abstract java.lang.Short getEVENT_TYPE_ENTER()
    abstract java.lang.Short getEVENT_TYPE_EXIT_DELAY()
    abstract java.lang.Short getEVENT_TYPE_FIRE()
    abstract java.lang.Short getEVENT_TYPE_GATE_CLOSE()
    abstract java.lang.Short getEVENT_TYPE_GATE_OPEN()
    abstract java.lang.Short getEVENT_TYPE_LOCK()
    abstract java.lang.Short getEVENT_TYPE_POLICE()
    abstract java.lang.Short getEVENT_TYPE_RFID()
    abstract java.lang.Short getEVENT_TYPE_TEST()
    abstract java.lang.Short getEVENT_TYPE_UNLOCK()
    abstract java.util.List getEventData()
    abstract java.lang.Short getEventType()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSequenceNumber()
    abstract void setDataType(java.lang.Short a)
    abstract void setEventData(java.util.List a)
    abstract void setEventType(java.lang.Short a)
    abstract void setSequenceNumber(java.lang.Short a)
}
