package me.biocomp.hubitat_ci.api.device_api.zwave.commands.notificationv8

import me.biocomp.hubitat_ci.api.device_api.zwave.Command

trait NotificationGet extends Command{
    abstract java.lang.Short getEvent() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getEvent()
    abstract java.lang.Short getNOTIFICATION_TYPE_ACCESS_CONTROL() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_ACCESS_CONTROL()
    abstract java.lang.Short getNOTIFICATION_TYPE_APPLIANCE() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv4.NotificationGet.getNOTIFICATION_TYPE_APPLIANCE()
    abstract java.lang.Short getNOTIFICATION_TYPE_BURGLAR() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_BURGLAR()
    abstract java.lang.Short getNOTIFICATION_TYPE_CLOCK() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_CLOCK()
    abstract java.lang.Short getNOTIFICATION_TYPE_CO() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_CO()
    abstract java.lang.Short getNOTIFICATION_TYPE_CO2() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_CO2()
    abstract java.lang.Short getNOTIFICATION_TYPE_EMERGENCY() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_EMERGENCY()
    abstract java.lang.Short getNOTIFICATION_TYPE_FIRST() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_FIRST()
    abstract java.lang.Short getNOTIFICATION_TYPE_GAS_ALARM() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv7.NotificationGet.getNOTIFICATION_TYPE_GAS_ALARM()
    abstract java.lang.Short getNOTIFICATION_TYPE_HEAT() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_HEAT()
    abstract java.lang.Short getNOTIFICATION_TYPE_HOME_HEALTH() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv4.NotificationGet.getNOTIFICATION_TYPE_HOME_HEALTH()
    abstract java.lang.Short getNOTIFICATION_TYPE_HOME_MONITORING() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv8.NotificationGet.getNOTIFICATION_TYPE_HOME_MONITORING()
    abstract java.lang.Short getNOTIFICATION_TYPE_IRRIGATION() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv7.NotificationGet.getNOTIFICATION_TYPE_IRRIGATION()
    abstract java.lang.Short getNOTIFICATION_TYPE_LIGHT_SENSOR() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv8.NotificationGet.getNOTIFICATION_TYPE_LIGHT_SENSOR()
    abstract java.lang.Short getNOTIFICATION_TYPE_PEST_CONTROL() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv8.NotificationGet.getNOTIFICATION_TYPE_PEST_CONTROL()
    abstract java.lang.Short getNOTIFICATION_TYPE_POWER_MANAGEMENT() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_POWER_MANAGEMENT()
    abstract java.lang.Short getNOTIFICATION_TYPE_RESERVED0() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_RESERVED0()
    abstract java.lang.Short getNOTIFICATION_TYPE_SIREN() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv6.NotificationGet.getNOTIFICATION_TYPE_SIREN()
    abstract java.lang.Short getNOTIFICATION_TYPE_SMOKE() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_SMOKE()
    abstract java.lang.Short getNOTIFICATION_TYPE_SYSTEM() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_SYSTEM()
    abstract java.lang.Short getNOTIFICATION_TYPE_WATER() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNOTIFICATION_TYPE_WATER()
    abstract java.lang.Short getNOTIFICATION_TYPE_WATER_QUALITY_MONITORING() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv8.NotificationGet.getNOTIFICATION_TYPE_WATER_QUALITY_MONITORING()
    abstract java.lang.Short getNOTIFICATION_TYPE_WATER_VALVE() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv7.NotificationGet.getNOTIFICATION_TYPE_WATER_VALVE()
    abstract java.lang.Short getNOTIFICATION_TYPE_WEATHER_ALARM() // Original: public static java.lang.Short hubitat.zwave.commands.notificationv7.NotificationGet.getNOTIFICATION_TYPE_WEATHER_ALARM()
    abstract java.lang.Short getNotificationType() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getNotificationType()
    abstract java.lang.Short getV1AlarmType() // Original: public java.lang.Short hubitat.zwave.commands.notificationv3.NotificationGet.getV1AlarmType()
    abstract void setEvent(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationGet.setEvent(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_ACCESS_CONTROL(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_ACCESS_CONTROL(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_APPLIANCE(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv4.NotificationGet.setNOTIFICATION_TYPE_APPLIANCE(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_BURGLAR(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_BURGLAR(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_CLOCK(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_CLOCK(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_CO(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_CO(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_CO2(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_CO2(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_EMERGENCY(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_EMERGENCY(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_FIRST(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_FIRST(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_GAS_ALARM(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv7.NotificationGet.setNOTIFICATION_TYPE_GAS_ALARM(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_HEAT(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_HEAT(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_HOME_HEALTH(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv4.NotificationGet.setNOTIFICATION_TYPE_HOME_HEALTH(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_HOME_MONITORING(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv8.NotificationGet.setNOTIFICATION_TYPE_HOME_MONITORING(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_IRRIGATION(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv7.NotificationGet.setNOTIFICATION_TYPE_IRRIGATION(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_LIGHT_SENSOR(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv8.NotificationGet.setNOTIFICATION_TYPE_LIGHT_SENSOR(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_PEST_CONTROL(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv8.NotificationGet.setNOTIFICATION_TYPE_PEST_CONTROL(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_POWER_MANAGEMENT(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_POWER_MANAGEMENT(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_RESERVED0(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_RESERVED0(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_SIREN(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv6.NotificationGet.setNOTIFICATION_TYPE_SIREN(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_SMOKE(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_SMOKE(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_SYSTEM(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_SYSTEM(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_WATER(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv3.NotificationGet.setNOTIFICATION_TYPE_WATER(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_WATER_QUALITY_MONITORING(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv8.NotificationGet.setNOTIFICATION_TYPE_WATER_QUALITY_MONITORING(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_WATER_VALVE(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv7.NotificationGet.setNOTIFICATION_TYPE_WATER_VALVE(java.lang.Short)
    abstract void setNOTIFICATION_TYPE_WEATHER_ALARM(java.lang.Short a) // Original: public static void hubitat.zwave.commands.notificationv7.NotificationGet.setNOTIFICATION_TYPE_WEATHER_ALARM(java.lang.Short)
    abstract void setNotificationType(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationGet.setNotificationType(java.lang.Short)
    abstract void setV1AlarmType(java.lang.Short a) // Original: public void hubitat.zwave.commands.notificationv3.NotificationGet.setV1AlarmType(java.lang.Short)
}
