package me.biocomp.hubitat_ci.api.device_api.zwave.commands.centralscenev2

trait CentralSceneNotification {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getKEY_HELD_DOWN()
    abstract java.lang.Short getKEY_PRESSED_1_TIME()
    abstract java.lang.Short getKEY_PRESSED_2_TIMES()
    abstract java.lang.Short getKEY_PRESSED_3_TIMES()
    abstract java.lang.Short getKEY_PRESSED_4_TIMES()
    abstract java.lang.Short getKEY_PRESSED_5_TIMES()
    abstract java.lang.Short getKEY_RELEASED()
    abstract java.lang.Short getKeyAttributes()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSceneNumber()
    abstract java.lang.Short getSequenceNumber()
    abstract void setKEY_HELD_DOWN(java.lang.Short a)
    abstract void setKEY_PRESSED_1_TIME(java.lang.Short a)
    abstract void setKEY_PRESSED_2_TIMES(java.lang.Short a)
    abstract void setKEY_PRESSED_3_TIMES(java.lang.Short a)
    abstract void setKEY_PRESSED_4_TIMES(java.lang.Short a)
    abstract void setKEY_PRESSED_5_TIMES(java.lang.Short a)
    abstract void setKEY_RELEASED(java.lang.Short a)
    abstract void setKeyAttributes(java.lang.Short a)
    abstract void setSceneNumber(java.lang.Short a)
    abstract void setSequenceNumber(java.lang.Short a)
}
