package me.biocomp.hubitat_ci.api.device_api.zwave.commands.dcpmonitorv1

trait DcpListReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getDay()
    abstract java.lang.Short getDcpId()
    abstract java.lang.Short getDurationHourTime()
    abstract java.lang.Short getDurationMinuteTime()
    abstract java.lang.Short getDurationSecondTime()
    abstract java.lang.Short getEventPriority()
    abstract java.lang.Short getHourLocalTime()
    abstract java.lang.Short getLoadShedding()
    abstract java.lang.Short getMinuteLocalTime()
    abstract java.lang.Short getMonth()
    abstract java.lang.Short getNumberOfDc()
    abstract java.util.List getPayload()
    abstract java.lang.Short getRandomizationInterval()
    abstract java.lang.Short getReportsToFollow()
    abstract java.lang.Short getSecondLocalTime()
    abstract java.lang.Short getStartAssociationGroup()
    abstract java.lang.Short getStartDay()
    abstract java.lang.Short getStartHourLocalTime()
    abstract java.lang.Short getStartMinuteLocalTime()
    abstract java.lang.Short getStartMonth()
    abstract java.lang.Short getStartSecondLocalTime()
    abstract java.lang.Integer getStartYear()
    abstract java.lang.Short getStopAssociationGroup()
    abstract java.lang.Integer getYear()
    abstract void setDay(java.lang.Short a)
    abstract void setDcpId(java.lang.Short a)
    abstract void setDurationHourTime(java.lang.Short a)
    abstract void setDurationMinuteTime(java.lang.Short a)
    abstract void setDurationSecondTime(java.lang.Short a)
    abstract void setEventPriority(java.lang.Short a)
    abstract void setHourLocalTime(java.lang.Short a)
    abstract void setLoadShedding(java.lang.Short a)
    abstract void setMinuteLocalTime(java.lang.Short a)
    abstract void setMonth(java.lang.Short a)
    abstract void setNumberOfDc(java.lang.Short a)
    abstract void setRandomizationInterval(java.lang.Short a)
    abstract void setReportsToFollow(java.lang.Short a)
    abstract void setSecondLocalTime(java.lang.Short a)
    abstract void setStartAssociationGroup(java.lang.Short a)
    abstract void setStartDay(java.lang.Short a)
    abstract void setStartHourLocalTime(java.lang.Short a)
    abstract void setStartMinuteLocalTime(java.lang.Short a)
    abstract void setStartMonth(java.lang.Short a)
    abstract void setStartSecondLocalTime(java.lang.Short a)
    abstract void setStartYear(java.lang.Integer a)
    abstract void setStopAssociationGroup(java.lang.Short a)
    abstract void setYear(java.lang.Integer a)
}
