package me.biocomp.hubitat_ci.api.device_api.zwave.commands.energyproductionv1

trait EnergyProductionReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getPARAMETER_NUMBER_ENERGY_PRODUCTION_TODAY()
    abstract java.lang.Short getPARAMETER_NUMBER_INSTANT_ENERGY_PRODUCTION()
    abstract java.lang.Short getPARAMETER_NUMBER_TOTAL_ENERGY_PRODUCTION()
    abstract java.lang.Short getPARAMETER_NUMBER_TOTAL_PRODUCTION_TIME()
    abstract java.lang.Short getParameterNumber()
    abstract java.util.List getPayload()
    abstract java.lang.Short getPrecision()
    abstract java.lang.Short getScale()
    abstract java.math.BigDecimal getScaledValue()
    abstract java.lang.Short getSize()
    abstract java.util.List getValue()
    abstract void setPARAMETER_NUMBER_ENERGY_PRODUCTION_TODAY(java.lang.Short a)
    abstract void setPARAMETER_NUMBER_INSTANT_ENERGY_PRODUCTION(java.lang.Short a)
    abstract void setPARAMETER_NUMBER_TOTAL_ENERGY_PRODUCTION(java.lang.Short a)
    abstract void setPARAMETER_NUMBER_TOTAL_PRODUCTION_TIME(java.lang.Short a)
    abstract void setParameterNumber(java.lang.Short a)
    abstract void setPrecision(java.lang.Short a)
    abstract void setScale(java.lang.Short a)
    abstract void setScaledValue(java.math.BigDecimal a)
    abstract void setSize(java.lang.Short a)
    abstract void setValue(java.util.List a)
}
