pool:
  name: Hosted VS2017
  demands: java

steps:
- task: Gradle@2
  displayName: 'gradlew build groovydoc'
  inputs:
    tasks: 'build groovydoc'
    pmdRunAnalysis: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'