package me.biocomp.hubitat_ci.api.device_api.zwave.commands.tarifftblmonitorv1

trait TariffTblCostReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getCostPrecision()
    abstract java.lang.Integer getCostValue()
    abstract java.lang.Integer getCurrency()
    abstract java.util.List getPayload()
    abstract java.lang.Short getRateParameterSetId()
    abstract java.lang.Short getRateType()
    abstract java.lang.Short getStartDay()
    abstract java.lang.Short getStartHourLocalTime()
    abstract java.lang.Short getStartMinuteLocalTime()
    abstract java.lang.Short getStartMonth()
    abstract java.lang.Integer getStartYear()
    abstract java.lang.Short getStopDay()
    abstract java.lang.Short getStopHourLocalTime()
    abstract java.lang.Short getStopMinuteLocalTime()
    abstract java.lang.Short getStopMonth()
    abstract java.lang.Integer getStopYear()
    abstract void setCostPrecision(java.lang.Short a)
    abstract void setCostValue(java.lang.Integer a)
    abstract void setCurrency(java.lang.Integer a)
    abstract void setRateParameterSetId(java.lang.Short a)
    abstract void setRateType(java.lang.Short a)
    abstract void setStartDay(java.lang.Short a)
    abstract void setStartHourLocalTime(java.lang.Short a)
    abstract void setStartMinuteLocalTime(java.lang.Short a)
    abstract void setStartMonth(java.lang.Short a)
    abstract void setStartYear(java.lang.Integer a)
    abstract void setStopDay(java.lang.Short a)
    abstract void setStopHourLocalTime(java.lang.Short a)
    abstract void setStopMinuteLocalTime(java.lang.Short a)
    abstract void setStopMonth(java.lang.Short a)
    abstract void setStopYear(java.lang.Integer a)
}
