package me.biocomp.hubitat_ci.api.device_api.zwave.commands.tarifftblmonitorv1

trait TariffTblSupplierReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Integer getCurrency()
    abstract java.lang.Short getDay()
    abstract java.lang.Short getHourLocalTime()
    abstract java.lang.Short getMinuteLocalTime()
    abstract java.lang.Short getMonth()
    abstract java.lang.Short getNumberOfSupplierCharacters()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSecondLocalTime()
    abstract java.lang.Short getStandingChargePeriod()
    abstract java.lang.Short getStandingChargePrecision()
    abstract java.lang.Integer getStandingChargeValue()
    abstract java.util.List getSupplierCharacter()
    abstract java.lang.Integer getYear()
    abstract void setCurrency(java.lang.Integer a)
    abstract void setDay(java.lang.Short a)
    abstract void setHourLocalTime(java.lang.Short a)
    abstract void setMinuteLocalTime(java.lang.Short a)
    abstract void setMonth(java.lang.Short a)
    abstract void setNumberOfSupplierCharacters(java.lang.Short a)
    abstract void setSecondLocalTime(java.lang.Short a)
    abstract void setStandingChargePeriod(java.lang.Short a)
    abstract void setStandingChargePrecision(java.lang.Short a)
    abstract void setStandingChargeValue(java.lang.Integer a)
    abstract void setSupplierCharacter(java.util.List a)
    abstract void setYear(java.lang.Integer a)
}
