package me.biocomp.hubitat_ci.api.device_api.zwave.commands.sensormultilevelv7

trait SensorMultilevelSupportedSensorReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getAirFlow()
    abstract java.lang.Boolean getAirTemperature()
    abstract java.lang.Boolean getAnglePosition()
    abstract java.lang.Boolean getAtmosphericPressure()
    abstract java.lang.Boolean getBarometricPressure()
    abstract java.lang.Boolean getBloodPressure()
    abstract java.lang.Boolean getBodyMass()
    abstract java.lang.Boolean getBodyMassIndex()
    abstract java.lang.Boolean getBoneMass()
    abstract java.lang.String getCMD()
    abstract java.lang.Boolean getCarbonDioxideLevel()
    abstract java.lang.Boolean getCarbonMonoxideLevel()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getCurrent()
    abstract java.lang.Boolean getDewPoint()
    abstract java.lang.Boolean getDirection()
    abstract java.lang.Boolean getDistance()
    abstract java.lang.Boolean getElectricalConductivity()
    abstract java.lang.Boolean getElectricalResistivity()
    abstract java.lang.Boolean getFatMass()
    abstract java.lang.Boolean getFormaldehydeLevel()
    abstract java.lang.Boolean getFrequency()
    abstract java.lang.Boolean getGeneralPurposeValue()
    abstract java.lang.Boolean getHeartRate()
    abstract java.lang.Boolean getHumidity()
    abstract java.lang.Boolean getLoudness()
    abstract java.lang.Boolean getLuminance()
    abstract java.lang.Boolean getMetabolicBasis()
    abstract java.lang.Boolean getMethaneLevel()
    abstract java.lang.Boolean getMoisture()
    abstract java.lang.Boolean getMuscleMass()
    abstract java.lang.Boolean getParticulateMaterLevel()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getPower()
    abstract java.lang.Boolean getRadonConcentration()
    abstract java.lang.Boolean getRainRate()
    abstract java.lang.Boolean getRotation()
    abstract java.lang.Boolean getSeismicIntensity()
    abstract java.lang.Boolean getSeismicMagnitude()
    abstract java.lang.Boolean getSoilHumidity()
    abstract java.lang.Boolean getSoilReactivity()
    abstract java.lang.Boolean getSoilSalinity()
    abstract java.lang.Boolean getSoilTemperature()
    abstract java.lang.Boolean getSolarRadiation()
    abstract java.lang.Boolean getTankCapacity()
    abstract java.lang.Boolean getTargetTemperature()
    abstract java.lang.Boolean getTideLevel()
    abstract java.lang.Boolean getTime()
    abstract java.lang.Boolean getUltraviolet()
    abstract java.lang.Boolean getVelocity()
    abstract java.lang.Boolean getVocLevel()
    abstract java.lang.Boolean getVoltage()
    abstract java.lang.Boolean getWaterTemperature()
    abstract java.lang.Boolean getWeight()
    abstract void setAirFlow(java.lang.Boolean a)
    abstract void setAirTemperature(java.lang.Boolean a)
    abstract void setAnglePosition(java.lang.Boolean a)
    abstract void setAtmosphericPressure(java.lang.Boolean a)
    abstract void setBarometricPressure(java.lang.Boolean a)
    abstract void setBloodPressure(java.lang.Boolean a)
    abstract void setBodyMass(java.lang.Boolean a)
    abstract void setBodyMassIndex(java.lang.Boolean a)
    abstract void setBoneMass(java.lang.Boolean a)
    abstract void setCarbonDioxideLevel(java.lang.Boolean a)
    abstract void setCarbonMonoxideLevel(java.lang.Boolean a)
    abstract void setCurrent(java.lang.Boolean a)
    abstract void setDewPoint(java.lang.Boolean a)
    abstract void setDirection(java.lang.Boolean a)
    abstract void setDistance(java.lang.Boolean a)
    abstract void setElectricalConductivity(java.lang.Boolean a)
    abstract void setElectricalResistivity(java.lang.Boolean a)
    abstract void setFatMass(java.lang.Boolean a)
    abstract void setFormaldehydeLevel(java.lang.Boolean a)
    abstract void setFrequency(java.lang.Boolean a)
    abstract void setGeneralPurposeValue(java.lang.Boolean a)
    abstract void setHeartRate(java.lang.Boolean a)
    abstract void setHumidity(java.lang.Boolean a)
    abstract void setLoudness(java.lang.Boolean a)
    abstract void setLuminance(java.lang.Boolean a)
    abstract void setMetabolicBasis(java.lang.Boolean a)
    abstract void setMethaneLevel(java.lang.Boolean a)
    abstract void setMoisture(java.lang.Boolean a)
    abstract void setMuscleMass(java.lang.Boolean a)
    abstract void setParticulateMaterLevel(java.lang.Boolean a)
    abstract void setPower(java.lang.Boolean a)
    abstract void setRadonConcentration(java.lang.Boolean a)
    abstract void setRainRate(java.lang.Boolean a)
    abstract void setRotation(java.lang.Boolean a)
    abstract void setSeismicIntensity(java.lang.Boolean a)
    abstract void setSeismicMagnitude(java.lang.Boolean a)
    abstract void setSoilHumidity(java.lang.Boolean a)
    abstract void setSoilReactivity(java.lang.Boolean a)
    abstract void setSoilSalinity(java.lang.Boolean a)
    abstract void setSoilTemperature(java.lang.Boolean a)
    abstract void setSolarRadiation(java.lang.Boolean a)
    abstract void setTankCapacity(java.lang.Boolean a)
    abstract void setTargetTemperature(java.lang.Boolean a)
    abstract void setTideLevel(java.lang.Boolean a)
    abstract void setTime(java.lang.Boolean a)
    abstract void setUltraviolet(java.lang.Boolean a)
    abstract void setVelocity(java.lang.Boolean a)
    abstract void setVocLevel(java.lang.Boolean a)
    abstract void setVoltage(java.lang.Boolean a)
    abstract void setWaterTemperature(java.lang.Boolean a)
    abstract void setWeight(java.lang.Boolean a)
}
