package me.biocomp.hubitat_ci.api.device_api.zwave.commands.sensorbinaryv2

trait SensorBinaryReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSENSOR_TYPE_AUX()
    abstract java.lang.Short getSENSOR_TYPE_CO()
    abstract java.lang.Short getSENSOR_TYPE_CO2()
    abstract java.lang.Short getSENSOR_TYPE_DOOR_WINDOW()
    abstract java.lang.Short getSENSOR_TYPE_FIRST()
    abstract java.lang.Short getSENSOR_TYPE_FREEZE()
    abstract java.lang.Short getSENSOR_TYPE_GENERAL_PURPOSE()
    abstract java.lang.Short getSENSOR_TYPE_GLASS_BREAK()
    abstract java.lang.Short getSENSOR_TYPE_HEAT()
    abstract java.lang.Short getSENSOR_TYPE_MOTION()
    abstract java.lang.Short getSENSOR_TYPE_SMOKE()
    abstract java.lang.Short getSENSOR_TYPE_TAMPER()
    abstract java.lang.Short getSENSOR_TYPE_TILT()
    abstract java.lang.Short getSENSOR_TYPE_WATER()
    abstract java.lang.Short getSENSOR_VALUE_DETECTED_AN_EVENT()
    abstract java.lang.Short getSENSOR_VALUE_IDLE()
    abstract java.lang.Short getSensorType()
    abstract java.lang.Short getSensorValue()
    abstract void setSENSOR_TYPE_AUX(java.lang.Short a)
    abstract void setSENSOR_TYPE_CO(java.lang.Short a)
    abstract void setSENSOR_TYPE_CO2(java.lang.Short a)
    abstract void setSENSOR_TYPE_DOOR_WINDOW(java.lang.Short a)
    abstract void setSENSOR_TYPE_FIRST(java.lang.Short a)
    abstract void setSENSOR_TYPE_FREEZE(java.lang.Short a)
    abstract void setSENSOR_TYPE_GENERAL_PURPOSE(java.lang.Short a)
    abstract void setSENSOR_TYPE_GLASS_BREAK(java.lang.Short a)
    abstract void setSENSOR_TYPE_HEAT(java.lang.Short a)
    abstract void setSENSOR_TYPE_MOTION(java.lang.Short a)
    abstract void setSENSOR_TYPE_SMOKE(java.lang.Short a)
    abstract void setSENSOR_TYPE_TAMPER(java.lang.Short a)
    abstract void setSENSOR_TYPE_TILT(java.lang.Short a)
    abstract void setSENSOR_TYPE_WATER(java.lang.Short a)
    abstract void setSENSOR_VALUE_DETECTED_AN_EVENT(java.lang.Short a)
    abstract void setSENSOR_VALUE_IDLE(java.lang.Short a)
    abstract void setSensorType(java.lang.Short a)
    abstract void setSensorValue(java.lang.Short a)
}
