package me.biocomp.hubitat_ci.api.device_api.zwave.commands.sensorbinaryv2

trait SensorBinarySupportedSensorReport {
    abstract java.lang.String format()
    abstract java.lang.Boolean getAux()
    abstract java.lang.String getCMD()
    abstract java.lang.Boolean getCo()
    abstract java.lang.Boolean getCo2()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Boolean getDoorwindow()
    abstract java.lang.Boolean getFirst()
    abstract java.lang.Boolean getFreeze()
    abstract java.lang.Boolean getGeneral()
    abstract java.lang.Boolean getGlassBreak()
    abstract java.lang.Boolean getHeat()
    abstract java.lang.Boolean getMotion()
    abstract java.util.List getPayload()
    abstract java.lang.Boolean getSmoke()
    abstract java.lang.Boolean getTamper()
    abstract java.lang.Boolean getTilt()
    abstract java.lang.Boolean getWater()
    abstract void setAux(java.lang.Boolean a)
    abstract void setCo(java.lang.Boolean a)
    abstract void setCo2(java.lang.Boolean a)
    abstract void setDoorwindow(java.lang.Boolean a)
    abstract void setFirst(java.lang.Boolean a)
    abstract void setFreeze(java.lang.Boolean a)
    abstract void setGeneral(java.lang.Boolean a)
    abstract void setGlassBreak(java.lang.Boolean a)
    abstract void setHeat(java.lang.Boolean a)
    abstract void setMotion(java.lang.Boolean a)
    abstract void setSmoke(java.lang.Boolean a)
    abstract void setTamper(java.lang.Boolean a)
    abstract void setTilt(java.lang.Boolean a)
    abstract void setWater(java.lang.Boolean a)
}
