package me.biocomp.hubitat_ci.api.device_api.zwave.commands.climatecontrolschedulev1

trait ScheduleSet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.util.List getPayload()
    abstract java.lang.Integer getSwitchpoint0()
    abstract java.lang.Integer getSwitchpoint1()
    abstract java.lang.Integer getSwitchpoint2()
    abstract java.lang.Integer getSwitchpoint3()
    abstract java.lang.Integer getSwitchpoint4()
    abstract java.lang.Integer getSwitchpoint5()
    abstract java.lang.Integer getSwitchpoint6()
    abstract java.lang.Integer getSwitchpoint7()
    abstract java.lang.Integer getSwitchpoint8()
    abstract java.lang.Short getWeekday()
    abstract void setSwitchpoint0(java.lang.Integer a)
    abstract void setSwitchpoint1(java.lang.Integer a)
    abstract void setSwitchpoint2(java.lang.Integer a)
    abstract void setSwitchpoint3(java.lang.Integer a)
    abstract void setSwitchpoint4(java.lang.Integer a)
    abstract void setSwitchpoint5(java.lang.Integer a)
    abstract void setSwitchpoint6(java.lang.Integer a)
    abstract void setSwitchpoint7(java.lang.Integer a)
    abstract void setSwitchpoint8(java.lang.Integer a)
    abstract void setWeekday(java.lang.Short a)
}
