package me.biocomp.hubitat_ci.api.device_api.zwave

interface Zwave {
    public abstract def getAlarmV1()
    public abstract def getAlarmV2()
    public abstract def getApplicationCapabilityV1()
    public abstract def getApplicationStatusV1()
    public abstract def getAssociationCommandConfigurationV1()
    public abstract def getAssociationGrpInfoV1()
    public abstract def getAssociationGrpInfoV2()
    public abstract def getAssociationGrpInfoV3()
    public abstract def getAssociationV1()
    public abstract def getAssociationV2()
    public abstract def getAssociationV3()
    public abstract def getAvContentDirectoryMdV1()
    public abstract def getAvContentSearchMdV1()
    public abstract def getAvRendererStatusV1()
    public abstract def getAvTaggingMdV1()
    public abstract def getBarrierOperatorV1()
    public abstract def getBasicTariffInfoV1()
    public abstract def getBasicV1()
    public abstract def getBasicV2()
    public abstract def getBasicWindowCoveringV1()
    public abstract def getBatteryV1()
    public abstract def getCentralSceneV1()
    public abstract def getCentralSceneV2()
    public abstract def getCentralSceneV3()
    public abstract def getChimneyFanV1()
    public abstract def getClimateControlScheduleV1()
    public abstract def getClockV1()
    public abstract Command getCommand(byte a,byte b,byte[] c)
    public abstract Command getCommand(java.lang.Short a, java.lang.Short b, java.util.List c)
    public abstract Command getCommand(java.lang.Short a, java.lang.Short b, java.util.List c, java.lang.Integer d)
    public abstract Command getCommand(byte a, byte b,byte[] c, java.lang.Integer d)
    public abstract def getConfigurationV1()
    public abstract def getConfigurationV2()
    public abstract def getControllerReplicationV1()
    public abstract def getCrc16EncapV1()
    public abstract def getDcpConfigV1()
    public abstract def getDcpMonitorV1()
    public abstract def getDeviceResetLocallyV1()
    public abstract def getDoorLockLoggingV1()
    public abstract def getDoorLockV1()
    public abstract def getEnergyProductionV1()
    public abstract def getEntryControlV1()
    public abstract def getFirmwareUpdateMdV1()
    public abstract def getFirmwareUpdateMdV2()
    public abstract def getFirmwareUpdateMdV3()
    public abstract def getFirmwareUpdateMdV4()
    public abstract def getFirmwareUpdateMdV5()
    public abstract def getFirmwareUpdateMdV6()
    public abstract def getGeographicLocationV1()
    public abstract def getGroupingNameV1()
    public abstract def getHailV1()
    public abstract def getHrvControlV1()
    public abstract def getHrvStatusV1()
    public abstract def getIndicatorV1()
    public abstract def getIndicatorV2()
    public abstract def getIndicatorV3()
    public abstract def getIpConfigurationV1()
    public abstract def getLanguageV1()
    public abstract def getLockV1()
    public abstract def getManufacturerSpecificV1()
    public abstract def getManufacturerSpecificV2()
    public abstract def getMeterPulseV1()
    public abstract def getMeterTblConfigV1()
    public abstract def getMeterTblMonitorV1()
    public abstract def getMeterTblMonitorV2()
    public abstract def getMeterTblPushV1()
    public abstract def getMeterV1()
    public abstract def getMeterV2()
    public abstract def getMeterV3()
    public abstract def getMeterV4()
    public abstract def getMeterV5()
    public abstract def getMtpWindowCoveringV1()
    public abstract def getMultiChannelAssociationV2()
    public abstract def getMultiChannelAssociationV3()
    public abstract def getMultiChannelAssociationV4()
    public abstract def getMultiChannelV2()
    public abstract def getMultiChannelV3()
    public abstract def getMultiChannelV4()
    public abstract def getMultiCmdV1()
    public abstract def getMultiInstanceAssociationV1()
    public abstract def getMultiInstanceV1()
    public abstract def getNetworkManagementInstallationMaintenanceV1()
    public abstract def getNetworkManagementInstallationMaintenanceV2()
    public abstract def getNodeNamingV1()
    public abstract def getNotificationV3()
    public abstract def getNotificationV4()
    public abstract def getNotificationV5()
    public abstract def getNotificationV6()
    public abstract def getNotificationV7()
    public abstract def getNotificationV8()
    public abstract def getPowerlevelV1()
    public abstract def getPrepaymentEncapsulationV1()
    public abstract def getPrepaymentV1()
    public abstract def getProprietaryV1()
    public abstract def getProtectionV1()
    public abstract def getProtectionV2()
    public abstract def getRateTblConfigV1()
    public abstract def getRateTblMonitorV1()
    public abstract def getRemoteAssociationActivateV1()
    public abstract def getRemoteAssociationV1()
    public abstract def getSceneActivationV1()
    public abstract def getSceneActuatorConfV1()
    public abstract def getSceneControllerConfV1()
    public abstract def getScheduleEntryLockV1()
    public abstract def getScheduleEntryLockV2()
    public abstract def getScheduleEntryLockV3()
    public abstract def getScheduleV1()
    public abstract def getScreenAttributesV1()
    public abstract def getScreenAttributesV2()
    public abstract def getScreenMdV1()
    public abstract def getScreenMdV2()
    public abstract def getSecurity2V1()
    public abstract def getSecurityPanelModeV1()
    public abstract def getSecurityPanelZoneSensorV1()
    public abstract def getSecurityPanelZoneV1()
    public abstract def getSecurityV1()
    public abstract def getSensorAlarmV1()
    public abstract def getSensorBinaryV1()
    public abstract def getSensorBinaryV2()
    public abstract def getSensorConfigurationV1()
    public abstract def getSensorMultilevelV1()
    public abstract def getSensorMultilevelV10()
    public abstract def getSensorMultilevelV11()
    public abstract def getSensorMultilevelV2()
    public abstract def getSensorMultilevelV3()
    public abstract def getSensorMultilevelV4()
    public abstract def getSensorMultilevelV5()
    public abstract def getSensorMultilevelV6()
    public abstract def getSensorMultilevelV7()
    public abstract def getSensorMultilevelV8()
    public abstract def getSensorMultilevelV9()
    public abstract def getSilenceAlarmV1()
    public abstract def getSimpleAvControlV1()
    public abstract def getSoundSwitchV1()
    public abstract def getSoundSwitchV2()
    public abstract def getSupervisionV1()
    public abstract def getSwitchAllV1()
    public abstract def getSwitchBinaryV1()
    public abstract def getSwitchBinaryV2()
    public abstract def getSwitchColorV1()
    public abstract def getSwitchColorV2()
    public abstract def getSwitchColorV3()
    public abstract def getSwitchMultilevelV1()
    public abstract def getSwitchMultilevelV2()
    public abstract def getSwitchMultilevelV3()
    public abstract def getSwitchMultilevelV4()
    public abstract def getSwitchToggleBinaryV1()
    public abstract def getSwitchToggleMultilevelV1()
    public abstract def getTariffConfigV1()
    public abstract def getTariffTblMonitorV1()
    public abstract def getThermostatFanModeV1()
    public abstract def getThermostatFanModeV2()
    public abstract def getThermostatFanModeV3()
    public abstract def getThermostatFanStateV1()
    public abstract def getThermostatHeatingV1()
    public abstract def getThermostatModeV1()
    public abstract def getThermostatModeV2()
    public abstract def getThermostatOperatingStateV1()
    public abstract def getThermostatOperatingStateV2()
    public abstract def getThermostatSetbackV1()
    public abstract def getThermostatSetpointV1()
    public abstract def getThermostatSetpointV2()
    public abstract def getTimeParametersV1()
    public abstract def getTimeV1()
    public abstract def getTimeV2()
    public abstract def getTransportServiceV1()
    public abstract def getUserCodeV1()
    public abstract def getVersionV1()
    public abstract def getVersionV2()
    public abstract def getVersionV3()
    public abstract def getWakeUpV1()
    public abstract def getWakeUpV2()
    public abstract Command parse(String s)
    public abstract Command parse(String s, boolean b)
    public abstract Command parse(String s, java.util.Map m)
    public abstract Command parse(String s, java.util.Map m, boolean b)
    abstract java.lang.Object getAntitheftUnlockV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getAntitheftUnlockV1()
    abstract java.lang.Object getAntitheftV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getAntitheftV1()
    abstract java.lang.Object getAntitheftV2() // Original: public static java.lang.trait hubitat.zwave.Zwave.getAntitheftV2()
    abstract java.lang.Object getAntitheftV3() // Original: public static java.lang.trait hubitat.zwave.Zwave.getAntitheftV3()
    abstract java.lang.Object getBatteryV2() // Original: public static java.lang.trait hubitat.zwave.Zwave.getBatteryV2()
    abstract java.lang.Object getBatteryV3() // Original: public static java.lang.trait hubitat.zwave.Zwave.getBatteryV3()
    abstract java.lang.Object getDmxV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getDmxV1()
    abstract java.lang.Object getHumidityControlModeV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getHumidityControlModeV1()
    abstract java.lang.Object getHumidityControlModeV2() // Original: public static java.lang.trait hubitat.zwave.Zwave.getHumidityControlModeV2()
    abstract java.lang.Object getHumidityControlOperatingStateV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getHumidityControlOperatingStateV1()
    abstract java.lang.Object getHumidityControlSetpointV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getHumidityControlSetpointV1()
    abstract java.lang.Object getHumidityControlSetpointV2() // Original: public static java.lang.trait hubitat.zwave.Zwave.getHumidityControlSetpointV2()
    abstract java.lang.Object getIrrigationV1() // Original: public static java.lang.trait hubitat.zwave.Zwave.getIrrigationV1()
    abstract java.lang.Object getSupervisionV2() // Original: public static java.lang.trait hubitat.zwave.Zwave.getSupervisionV2()
    abstract java.lang.Object getThermostatFanModeV4() // Original: public static java.lang.trait hubitat.zwave.Zwave.getThermostatFanModeV4()
    abstract java.lang.Object getThermostatFanModeV5() // Original: public static java.lang.trait hubitat.zwave.Zwave.getThermostatFanModeV5()
    abstract java.lang.Object getThermostatFanStateV2() // Original: public static java.lang.trait hubitat.zwave.Zwave.getThermostatFanStateV2()
    abstract java.lang.Object getThermostatModeV3() // Original: public static java.lang.trait hubitat.zwave.Zwave.getThermostatModeV3()
    abstract java.lang.Object getThermostatSetpointV3() // Original: public static java.lang.trait hubitat.zwave.Zwave.getThermostatSetpointV3()
    abstract java.lang.Object getWakeUpV3() // Original: public static java.lang.trait hubitat.zwave.Zwave.getWakeUpV3()
}

