package me.biocomp.hubitat_ci.api.device_api.zwave.commands.powerlevelv1

trait PowerlevelSet {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getPOWER_LEVEL_MINUS1DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS2DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS3DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS4DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS5DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS6DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS7DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS8DBM()
    abstract java.lang.Short getPOWER_LEVEL_MINUS9DBM()
    abstract java.lang.Short getPOWER_LEVEL_NORMALPOWER()
    abstract java.util.List getPayload()
    abstract java.lang.Short getPowerLevel()
    abstract java.lang.Short getTimeout()
    abstract void setPOWER_LEVEL_MINUS1DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS2DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS3DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS4DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS5DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS6DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS7DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS8DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_MINUS9DBM(java.lang.Short a)
    abstract void setPOWER_LEVEL_NORMALPOWER(java.lang.Short a)
    abstract void setPowerLevel(java.lang.Short a)
    abstract void setTimeout(java.lang.Short a)
}
