package me.biocomp.hubitat_ci.api.device_api.zwave.commands.firmwareupdatemdv6

trait FirmwareUpdateMdStatusReport {
    abstract java.lang.String format()
    abstract java.lang.String getCMD()
    abstract java.lang.Short getCommandClassId()
    abstract java.lang.Short getCommandId()
    abstract java.lang.Short getINVALID_HARDWARE_VERSION()
    abstract java.util.List getPayload()
    abstract java.lang.Short getSTATUS_ANOTHER_TRANSFER_IN_PROGRESS()
    abstract java.lang.Short getSTATUS_IINVALID_FRAGMENT_SIZE()
    abstract java.lang.Short getSTATUS_INSUFFICIENT_BATTERY_LEVEL()
    abstract java.lang.Short getSTATUS_NOT_DOWNLOADABLE()
    abstract java.lang.Short getSTATUS_SUCCESSFULLY()
    abstract java.lang.Short getSTATUS_UNABLE_TO_RECEIVE()
    abstract java.lang.Short getSTATUS_UNABLE_TO_RECEIVE_WITHOUT_CHECKSUM_ERROR()
    abstract java.lang.Short getStatus()
    abstract void setINVALID_HARDWARE_VERSION(java.lang.Short a)
    abstract void setSTATUS_ANOTHER_TRANSFER_IN_PROGRESS(java.lang.Short a)
    abstract void setSTATUS_IINVALID_FRAGMENT_SIZE(java.lang.Short a)
    abstract void setSTATUS_INSUFFICIENT_BATTERY_LEVEL(java.lang.Short a)
    abstract void setSTATUS_NOT_DOWNLOADABLE(java.lang.Short a)
    abstract void setSTATUS_SUCCESSFULLY(java.lang.Short a)
    abstract void setSTATUS_UNABLE_TO_RECEIVE(java.lang.Short a)
    abstract void setSTATUS_UNABLE_TO_RECEIVE_WITHOUT_CHECKSUM_ERROR(java.lang.Short a)
    abstract void setStatus(java.lang.Short a)
}
